import type { Path } from "./types";

export const paths: Path[] = [
  { repo: "abap", title: "ABAP", icon: "used/pack-10/046-rum.svg", categories: ["other"], legacyViews: 3868 },
  { repo: "ableton-live", title: "Ableton Live", icon: "used/pack-5/039-flask.svg", platform: ["macos", "windows"], synonyms: ["daw", "music production"], categories: ["other"], legacyViews: 4871 },
  { repo: "abricotine", title: "Abricotine", icon: "used/pack-9/013-poison.svg", synonyms: ["markdown"], categories: ["editor"], legacyViews: 983 },
  { repo: "acs", title: "ACS", icon: "used/pack-3/032-pendant.svg", categories: ["other"], legacyViews: 0 },
  { repo: "adiirc", title: "AdiIRC", icon: "used/pack-8/044-rocket.svg", platform: ["windows"], synonyms: ["irc", "chat"], categories: ["social"], legacyViews: 0 },
  { repo: "adminer", title: "Adminer", icon: "used/pack-8/005-moon.svg", synonyms: ["database", "sql", "mysql", "phpmyadmin"], categories: ["other"], legacyViews: 3123 },
  { repo: "adobe", title: "Adobe", icon: "used/pack-6/039-zombie.svg", platform: ["macos", "windows"], synonyms: ["photoshop", "illustrator", "xd", "creative cloud"], categories: ["other"], legacyViews: 11244 },
  { repo: "adventofcode", title: "Advent of Code", icon: "used/pack-2/009-tetris.svg", synonyms: ["aoc", "coding challenge"], categories: ["other"], legacyViews: 0 },
  { repo: "aerc", title: "aerc", icon: "used/pack-4/010-centaur.svg", synonyms: ["email", "mail client"], categories: ["other"], legacyViews: 0 },
  { repo: "alacritty", title: "Alacritty", icon: "used/pack-6/004-reaper.svg", synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 30582 },
  { repo: "albert", title: "Albert", icon: "used/pack-7/011-food.svg", platform: ["linux"], synonyms: ["launcher", "spotlight"], categories: ["other"], legacyViews: 1470 },
  { repo: "alfred", title: "Alfred", icon: "used/pack-5/019-wizard hat.svg", platform: ["macos"], synonyms: ["launcher", "spotlight", "productivity"], categories: ["other"], legacyViews: 18846 },
  { repo: "aliucord", title: "Aliucord", icon: "used/pack-9/027-candy-cane.svg", synonyms: ["discord"], categories: ["social"], legacyViews: 2845 },
  { repo: "amfora", title: "Amfora", icon: "used/pack-9/011-bucket.svg", synonyms: ["gemini", "browser"], categories: ["terminal"], legacyViews: 470 },
  { repo: "anne-pro-2", title: "Anne Pro 2", icon: "used/pack-9/043-halloween.svg", synonyms: ["keyboard", "obinskit"], categories: ["other"], legacyViews: 0 },
  { repo: "anytype", title: "Anytype", icon: "used/pack-2/008-cards.svg", synonyms: ["notes", "knowledge base", "notion"], categories: ["other"], legacyViews: 0 },
  { repo: "apollo", title: "Apollo", icon: "used/pack-8/001-space.svg", platform: ["macos"], synonyms: ["reddit"], categories: ["social"], legacyViews: 1076 },
  { repo: "apt", title: "apt", icon: "used/pack-2/040-game controller.svg", platform: ["linux"], synonyms: ["apt-get", "package manager", "debian"], categories: ["terminal"], legacyViews: 0 },
  { repo: "archive-of-our-own", title: "Archive of Our Own", icon: "used/pack-3/008-chest.svg", synonyms: ["ao3", "fanfiction"], categories: ["service"], legacyViews: 438 },
  { repo: "arduino-ide", title: "Arduino IDE", icon: "used/pack-1/001-gallows.svg", synonyms: ["microcontroller"], categories: ["ide"], legacyViews: 12946 },
  { repo: "arduino-pro-ide", title: "Arduino Pro IDE", icon: "used/pack-7/014-cauldron.svg", synonyms: ["microcontroller"], categories: ["ide"], legacyViews: 2250 },
  { repo: "aseprite", title: "Aseprite", icon: "used/pack-8/006-asteroid.svg", synonyms: ["pixel art", "sprite editor"], categories: ["other"], legacyViews: 6361 },
  { repo: "atom", title: "Atom", icon: "used/pack-1/005-potion.svg", synonyms: ["text editor", "github"], categories: ["editor"], legacyViews: 81218 },
  { repo: "audacity", title: "Audacity", icon: "used/pack-3/020-magic-ball.svg", synonyms: ["audio editor", "recording"], categories: ["other"], legacyViews: 0 },
  { repo: "auto-ao3-app", title: "AutoAO3App", icon: "used/pack-5/028-magic hat.svg", synonyms: ["ao3", "archive of our own"], categories: ["other"], legacyViews: 102 },
  { repo: "bandcamp", title: "Bandcamp", icon: "used/pack-4/002-grapes.svg", synonyms: ["music", "streaming"], categories: ["service"], legacyViews: 0 },
  { repo: "base16-dracula-scheme", title: "Base16", icon: "used/pack-6/030-graveyard.svg", synonyms: ["color scheme", "theme"], categories: ["other"], legacyViews: 9431 },
  { repo: "bashtop", title: "Bashtop", icon: "used/pack-7/044-monster.svg", platform: ["linux", "macos"], synonyms: ["system monitor", "htop", "btop"], categories: ["terminal"], legacyViews: 3631 },
  { repo: "bbedit", title: "BBEdit", icon: "used/pack-4/041-cyclops.svg", platform: ["macos"], synonyms: ["text editor"], categories: ["editor"], legacyViews: 6306 },
  { repo: "beamer", title: "Beamer", icon: "used/pack-10/048-zombie.svg", synonyms: ["latex", "presentation"], categories: ["other"], legacyViews: 1513 },
  { repo: "bear", title: "Bear", icon: "used/pack-1/008-tree.svg", platform: ["macos"], synonyms: ["notes", "markdown"], categories: ["editor"], legacyViews: 3446 },
  { repo: "bemenu", title: "bemenu", icon: "used/pack-7/027-gifts.svg", platform: ["linux", "macos"], synonyms: ["menu", "launcher", "dmenu"], categories: ["other"], legacyViews: 1056 },
  { repo: "bettercanvas", title: "BetterCanvas", icon: "used/pack-2/047-virtual reality.svg", synonyms: ["canvas lms"], categories: ["other"], legacyViews: 0 },
  { repo: "betterdiscord", title: "BetterDiscord", icon: "used/pack-2/030-game-controller.svg", synonyms: ["discord"], categories: ["social"], legacyViews: 37345 },
  { repo: "beyond-compare-4", title: "Beyond Compare 4", icon: "used/pack-10/050-scarecrow.svg", synonyms: ["diff", "merge"], categories: ["other"], legacyViews: 2092 },
  { repo: "blender", title: "Blender", icon: "used/pack-2/029-bomb.svg", synonyms: ["3d", "modeling", "animation"], categories: ["other"], legacyViews: 10649 },
  { repo: "blink-shell", title: "Blink Shell", icon: "used/pack-2/038-3d glasses.svg", synonyms: ["ssh"], categories: ["terminal"], legacyViews: 263 },
  { repo: "blockbench", title: "Blockbench", icon: "used/pack-2/034-video card.svg", synonyms: ["3d", "minecraft", "modeling"], categories: ["other"], legacyViews: 0 },
  { repo: "bobthefish", title: "bobthefish", icon: "used/pack-10/001-witch.svg", synonyms: ["fish", "prompt", "theme"], categories: ["terminal"], legacyViews: 529 },
  { repo: "bookwyrm", title: "BookWyrm", icon: "used/pack-4/012-laurel.svg", synonyms: ["goodreads", "books"], categories: ["service"], legacyViews: 0 },
  { repo: "brackets", title: "Brackets", icon: "used/pack-4/043-minotaur.svg", synonyms: ["text editor", "adobe"], categories: ["editor"], legacyViews: 27630 },
  { repo: "bspwm", title: "bspwm", icon: "used/pack-6/022-candle.svg", platform: ["linux"], synonyms: ["window manager", "tiling"], categories: ["other"], legacyViews: 8603 },
  { repo: "btcpay-server", title: "BTCPay Server", icon: "used/pack-9/048-bat.svg", synonyms: ["bitcoin", "crypto", "payment"], categories: ["service"], legacyViews: 398 },
  { repo: "cadzinho", title: "CadZinho", icon: "used/pack-8/049-astronaut.svg", synonyms: ["cad", "drafting"], categories: ["other"], legacyViews: 0 },
  { repo: "calibre", title: "Calibre", icon: "used/pack-11/049-robot.svg", synonyms: ["ebook", "epub"], categories: ["other"], legacyViews: 0 },
  { repo: "campfire", title: "Campfire", icon: "used/pack-7/020-lantern.svg", synonyms: ["chat"], categories: ["social"], legacyViews: 137 },
  { repo: "caprine-messenger", title: "Caprine Messenger", icon: "used/pack-10/033-crow.svg", synonyms: ["facebook", "messenger"], categories: ["social"], legacyViews: 608 },
  { repo: "castero", title: "Castero", icon: "used/pack-8/022-satellite dish.svg", synonyms: ["rss", "podcast", "tui"], categories: ["terminal"], legacyViews: 0 },
  { repo: "cava", title: "Cava", icon: "used/pack-3/038-rainbow.svg", platform: ["linux", "macos"], synonyms: ["audio visualizer"], categories: ["terminal"], legacyViews: 173 },
  { repo: "chatgpt", title: "ChatGPT", icon: "used/pack-12/003-devil.svg", synonyms: ["ai", "openai", "gpt"], categories: ["service"], legacyViews: 0 },
  { repo: "chatterino", title: "Chatterino", icon: "used/pack-3/031-mushroom.svg", synonyms: ["twitch", "chat"], categories: ["social"], legacyViews: 0 },
  { repo: "cider", title: "Cider", icon: "used/pack-1/009-costume.svg", synonyms: ["apple music"], categories: ["other"], legacyViews: 732 },
  { repo: "cli-visualizer", title: "Cli-Visualizer", icon: "used/pack-2/006-puzzle.svg", synonyms: ["audio visualizer"], categories: ["terminal"], legacyViews: 0 },
  { repo: "clone-hero", title: "Clone Hero", icon: "used/pack-2/036-game-controller.svg", synonyms: ["guitar hero"], categories: ["other"], legacyViews: 840 },
  { repo: "cmder", title: "Cmder", icon: "used/pack-1/006-night.svg", platform: ["windows"], synonyms: ["console emulator"], categories: ["terminal"], legacyViews: 17970 },
  { repo: "coda", title: "Coda", icon: "used/pack-1/013-lollipop.svg", platform: ["macos"], synonyms: ["web editor"], categories: ["editor"], legacyViews: 8975 },
  { repo: "codeblocks", title: "Code::Blocks", icon: "used/pack-5/010-toolbox.svg", synonyms: ["c++", "compiler"], categories: ["ide"], legacyViews: 20722 },
  { repo: "codeforces", title: "Codeforces", icon: "used/pack-2/002-domino.svg", synonyms: ["competitive programming", "cp"], categories: ["service"], legacyViews: 0 },
  { repo: "codepen", title: "CodePen", icon: "used/pack-9/049-magic-wand.svg", synonyms: ["html", "css", "javascript", "playground"], categories: ["service"], legacyViews: 476 },
  { repo: "coderunner", title: "CodeRunner", icon: "used/pack-10/024-cupcake.svg", platform: ["macos"], categories: ["editor"], legacyViews: 494 },
  { repo: "color-slurp", title: "ColorSlurp", icon: "used/pack-2/013-darts.svg", platform: ["macos"], synonyms: ["color picker", "eyedropper"], categories: ["other"], legacyViews: 154 },
  { repo: "colorls", title: "colorls", icon: "used/pack-2/026-building.svg", synonyms: ["ls"], categories: ["terminal"], legacyViews: 6673 },
  { repo: "conemu", title: "ConEmu", icon: "used/pack-1/010-trident.svg", platform: ["windows"], synonyms: ["console"], categories: ["terminal"], legacyViews: 32516 },
  { repo: "copyq", title: "CopyQ", icon: "used/pack-8/009-robot.svg", synonyms: ["clipboard", "clipboard manager"], categories: ["other"], legacyViews: 1497 },
  { repo: "cosmic-terminal", title: "Cosmic Terminal", icon: "used/pack-12/037-alien.svg", synonyms: ["pop os", "system76"], categories: ["terminal"], legacyViews: 0 },
  { repo: "coteditor", title: "CotEditor", icon: "used/pack-1/026-mummy.svg", platform: ["macos"], synonyms: ["text editor"], categories: ["editor"], legacyViews: 1719 },
  { repo: "couscous", title: "Couscous", icon: "used/pack-1/024-tombstone-1.svg", synonyms: ["static site", "documentation"], categories: ["other"], legacyViews: 2001 },
  { repo: "cryptowatch", title: "Cryptowatch", icon: "used/pack-7/037-halloween.svg", synonyms: ["crypto", "trading", "bitcoin"], categories: ["service"], legacyViews: 1589 },
  { repo: "cursor", title: "Cursor", icon: "used/pack-8/029-telescope.svg", synonyms: ["ai", "code editor"], categories: ["editor"], legacyViews: 0 },
  { repo: "cutter", title: "Cutter", icon: "used/pack-3/006-cards.svg", synonyms: ["reverse engineering", "radare2"], categories: ["other"], legacyViews: 0 },
  { repo: "delphi", title: "Delphi", icon: "used/pack-9/032-tree.svg", synonyms: ["pascal", "rad studio"], categories: ["ide"], legacyViews: 875 },
  { repo: "dev-cpp", title: "Dev-C++", icon: "used/pack-9/021-scream.svg", platform: ["windows"], synonyms: ["c++", "compiler"], categories: ["ide"], legacyViews: 9935 },
  { repo: "dircolors", title: ".dircolors", icon: "used/pack-9/037-paper-bag.svg", platform: ["linux"], synonyms: ["ls colors"], categories: ["terminal"], legacyViews: 895 },
  { repo: "directory-opus", title: "Directory Opus", icon: "used/pack-2/033-tic tac toe.svg", platform: ["windows"], synonyms: ["file manager"], categories: ["other"], legacyViews: 0 },
  { repo: "discordbotmaker", title: "Discord Bot Maker", icon: "used/pack-10/041-potion.svg", platform: ["windows"], synonyms: ["discord", "bot"], categories: ["other"], legacyViews: 2299 },
  { repo: "discourse", title: "Discourse", icon: "used/pack-7/032-bat.svg", synonyms: ["forum"], categories: ["service"], legacyViews: 3377 },
  { repo: "ditto", title: "Ditto", icon: "used/pack-7/023-balloons.svg", platform: ["windows"], synonyms: ["clipboard", "clipboard manager"], categories: ["other"], legacyViews: 1117 },
  { repo: "django-admin", title: "Django Admin", icon: "used/pack-3/039-ring.svg", synonyms: ["django", "python", "admin panel"], categories: ["service"], legacyViews: 0 },
  { repo: "dmenu", title: "Dmenu", icon: "used/pack-1/012-bag.svg", platform: ["linux"], synonyms: ["launcher", "menu"], categories: ["other"], legacyViews: 352 },
  { repo: "docker", title: "Docker", icon: "used/pack-8/020-space capsule.svg", synonyms: ["container", "containerization"], categories: ["other"], legacyViews: 0 },
  { repo: "doom-emacs", title: "DOOM Emacs", icon: "used/pack-7/007-living-dead.svg", synonyms: ["emacs"], categories: ["editor"], legacyViews: 6209 },
  { repo: "dRacula", title: "R", icon: "used/pack-13/002-dracula-hex.svg", synonyms: ["rstats", "statistics"], categories: ["other"], legacyViews: 572 },
  { repo: "drafts", title: "Drafts", icon: "used/pack-5/006-treasure-chest.svg", platform: ["macos"], synonyms: ["notes", "markdown"], categories: ["editor"], legacyViews: 345 },
  { repo: "duckduckgo", title: "DuckDuckGo", icon: "used/pack-1/002-coffin.svg", synonyms: ["search engine", "ddg"], categories: ["service"], legacyViews: 12132 },
  { repo: "dunst", title: "Dunst", icon: "used/pack-7/033-trident.svg", platform: ["linux"], synonyms: ["notification", "notifications"], categories: ["other"], legacyViews: 3327 },
  { repo: "duolingo", title: "Duolingo", icon: "used/pack-12/015-athena.svg", synonyms: ["language learning"], categories: ["service"], legacyViews: 0 },
  { repo: "dwarf-fortress", title: "Dwarf Fortress", icon: "used/pack-10/038-dwarf.svg", synonyms: ["game"], categories: ["other"], legacyViews: 1011 },
  { repo: "dyalog", title: "Dyalog APL", icon: "used/pack-4/027-flag.svg", synonyms: ["apl"], categories: ["ide"], legacyViews: 77 },
  { repo: "eclipse", title: "Eclipse", icon: "used/pack-7/008-full moon.svg", synonyms: ["java"], categories: ["ide"], legacyViews: 61636 },
  { repo: "editplus", title: "Editplus", icon: "used/pack-1/023-bones.svg", platform: ["windows"], synonyms: ["text editor"], categories: ["editor"], legacyViews: 2688 },
  { repo: "em-client", title: "eM Client", icon: "used/pack-9/009-broomstick.svg", platform: ["macos", "windows"], synonyms: ["email", "mail"], categories: ["other"], legacyViews: 885 },
  { repo: "emacs", title: "Emacs", icon: "used/pack-1/018-devil.svg", synonyms: ["text editor"], categories: ["editor"], legacyViews: 82188 },
  { repo: "everythingtoolbar", title: "EverythingToolbar", icon: "used/pack-7/019-mask.svg", platform: ["windows"], synonyms: ["search", "everything"], categories: ["other"], legacyViews: 1796 },
  { repo: "evidence", title: "Evidence", icon: "used/pack-2/015-dice.svg", synonyms: ["bi", "business intelligence"], categories: ["service"], legacyViews: 0 },
  { repo: "exa", title: "exa", icon: "used/pack-10/014-vampire.svg", platform: ["linux", "macos"], synonyms: ["ls"], categories: ["terminal"], legacyViews: 0 },
  { repo: "eza", title: "eza", icon: "used/pack-2/012-air hockey.svg", synonyms: ["ls", "exa"], categories: ["terminal"], legacyViews: 0 },
  { repo: "facebook-messenger", title: "Facebook Messenger", icon: "used/pack-13/033-balloon.svg", synonyms: ["messenger", "facebook"], categories: ["social"], legacyViews: 0 },
  { repo: "facebook", title: "Facebook", icon: "used/pack-8/035-globe.svg", synonyms: ["social network"], categories: ["service"], legacyViews: 0 },
  { repo: "fedilab", title: "Fedilab", icon: "used/pack-8/013-capsule.svg", synonyms: ["mastodon", "fediverse"], categories: ["social"], legacyViews: 7 },
  { repo: "fig", title: "Fig", icon: "used/pack-9/026-castle.svg", platform: ["macos"], synonyms: ["autocomplete", "terminal"], categories: ["terminal"], legacyViews: 795 },
  { repo: "figma", title: "Figma", icon: "used/pack-4/044-werewolf.svg", synonyms: ["design", "ui", "ux"], categories: ["service"], legacyViews: 10188 },
  { repo: "files", title: "Files", icon: "used/pack-10/016-pumpkin.svg", platform: ["windows"], synonyms: ["file manager", "explorer"], categories: ["other"], legacyViews: 7582 },
  { repo: "firefox", title: "Firefox", icon: "used/pack-1/028-finger.svg", synonyms: ["mozilla", "web browser"], categories: ["browser"], legacyViews: 42358 },
  { repo: "fish", title: "Fish", icon: "used/pack-1/011-poison.svg", synonyms: ["shell", "fish shell"], categories: ["terminal"], legacyViews: 12681 },
  { repo: "fl-studio-21", title: "FL Studio 21", icon: "used/pack-4/022-harp.svg", platform: ["windows", "macos"], synonyms: ["daw", "fruity loops", "music production"], categories: ["other"], legacyViews: 709 },
  { repo: "flarum", title: "Flarum", icon: "used/pack-10/030-lantern.svg", synonyms: ["forum"], categories: ["service"], legacyViews: 888 },
  { repo: "florisboard", title: "FlorisBoard", icon: "used/pack-9/024-candle.svg", synonyms: ["keyboard", "android"], categories: ["other"], legacyViews: 1304 },
  { repo: "flowlab", title: "Flowlab", icon: "used/pack-2/007-mobile-game.svg", synonyms: ["game engine"], categories: ["service"], legacyViews: 485 },
  { repo: "fluent-terminal", title: "Fluent Terminal", icon: "used/pack-1/049-bats.svg", platform: ["windows"], categories: ["terminal"], legacyViews: 9809 },
  { repo: "fluxbox", title: "Fluxbox", icon: "used/pack-3/021-potion.svg", platform: ["linux"], synonyms: ["window manager"], categories: ["other"], legacyViews: 0 },
  { repo: "fman", title: "fman", icon: "used/pack-8/028-alien.svg", synonyms: ["file manager"], categories: ["other"], legacyViews: 1145 },
  { repo: "fontforge", title: "FontForge", icon: "used/pack-4/019-parthenon.svg", synonyms: ["font editor"], categories: ["other"], legacyViews: 0 },
  { repo: "foot", title: "foot", icon: "used/pack-6/042-corpse.svg", platform: ["linux"], synonyms: ["terminal emulator", "wayland"], categories: ["terminal"], legacyViews: 860 },
  { repo: "forklift", title: "ForkLift", icon: "used/pack-13/023-cemetery.svg", platform: ["macos"], synonyms: ["ftp", "file manager"], categories: ["other"], legacyViews: 0 },
  { repo: "freecad", title: "FreeCAD", icon: "used/pack-2/018-jenga.svg", synonyms: ["cad", "3d"], categories: ["other"], legacyViews: 1917 },
  { repo: "freetube", title: "FreeTube", icon: "used/pack-8/023-monkey.svg", synonyms: ["youtube"], categories: ["other"], legacyViews: 0 },
  { repo: "funkwhale", title: "Funkwhale", icon: "used/pack-9/044-scythe.svg", synonyms: ["music", "streaming"], categories: ["service"], legacyViews: 455 },
  { repo: "fuzzel", title: "fuzzel", icon: "used/pack-11/046-robot.svg", platform: ["linux"], synonyms: ["launcher", "wayland", "dmenu"], categories: ["other"], legacyViews: 0 },
  { repo: "fzf", title: "FZF", icon: "used/pack-10/027-eyeball.svg", synonyms: ["fuzzy finder", "search"], categories: ["terminal"], legacyViews: 1745 },
  { repo: "gajim", title: "Gajim", icon: "used/pack-10/005-bat.svg", synonyms: ["xmpp", "jabber", "chat"], categories: ["social"], legacyViews: 386 },
  { repo: "gamemaker-studio", title: "GameMaker Studio", icon: "used/pack-1/031-serial-killer.svg", synonyms: ["game engine", "gms"], categories: ["ide"], legacyViews: 8991 },
  { repo: "gamepad-viewer", title: "Gamepad Viewer", icon: "used/pack-2/010-game-controller.svg", synonyms: ["controller", "gamepad"], categories: ["other"], legacyViews: 1633 },
  { repo: "geany", title: "Geany", icon: "used/pack-3/009-crystal-ball.svg", synonyms: ["text editor", "ide"], categories: ["editor"], legacyViews: 5988 },
  { repo: "gedit", title: "Gedit", icon: "used/pack-1/036-spellbook.svg", platform: ["linux"], synonyms: ["text editor", "gnome"], categories: ["editor"], legacyViews: 34791 },
  { repo: "gemini", title: "Gemini", icon: "used/pack-12/038-genie.svg", synonyms: ["google", "ai"], categories: ["service"], legacyViews: 0 },
  { repo: "gh-dash", title: "GH-Dash", icon: "used/pack-3/046-trick.svg", synonyms: ["github", "dashboard"], categories: ["terminal"], legacyViews: 0 },
  { repo: "gh-pages", title: "GitHub Pages", icon: "used/pack-1/037-candies.svg", synonyms: ["github", "hosting"], categories: ["service"], legacyViews: 17104 },
  { repo: "ghostty", title: "Ghostty", icon: "used/pack-10/037-ghost-1.svg", synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 0 },
  { repo: "ghostwriter", title: "ghostwriter", icon: "used/pack-10/012-ghost.svg", platform: ["windows", "linux"], synonyms: ["markdown", "text editor"], categories: ["editor"], legacyViews: 1154 },
  { repo: "gimp", title: "GIMP", icon: "used/pack-5/001-magic-wand.svg", synonyms: ["image editor", "photoshop"], categories: ["other"], legacyViews: 860 },
  { repo: "git", title: "Git", icon: "used/pack-3/003-book.svg", synonyms: ["version control", "vcs"], categories: ["terminal"], legacyViews: 3847 },
  { repo: "github", title: "GitHub", icon: "used/pack-7/045-cat.svg", synonyms: ["git"], categories: ["service"], legacyViews: 7033 },
  { repo: "gitk", title: "Gitk", icon: "used/pack-5/020-saw.svg", synonyms: ["git", "gui"], categories: ["other"], legacyViews: 10713 },
  { repo: "gitkraken", title: "GitKraken", icon: "used/pack-9/033-bug.svg", synonyms: ["git", "gui"], categories: ["other"], legacyViews: 1308 },
  { repo: "gitlab", title: "GitLab", icon: "used/pack-10/009-cat.svg", synonyms: ["git"], categories: ["service"], legacyViews: 1776 },
  { repo: "gitroll", title: "Gitroll", icon: "used/pack-2/004-roulette.svg", synonyms: ["git", "developer profile"], categories: ["service"], legacyViews: 0 },
  { repo: "gmk", title: "GMK", icon: "used/pack-4/016-axe.svg", synonyms: ["keyboard", "keycaps"], categories: ["other"], legacyViews: 19006 },
  { repo: "gnome-terminal", title: "Gnome Terminal", icon: "used/pack-6/040-crow.svg", platform: ["linux"], synonyms: ["gnome"], categories: ["terminal"], legacyViews: 179027 },
  { repo: "go-access", title: "GoAccess", icon: "used/pack-3/023-magic-lamp.svg", synonyms: ["log analyzer", "analytics"], categories: ["terminal"], legacyViews: 0 },
  { repo: "godot", title: "Godot", icon: "used/pack-7/024-skeleton.svg", synonyms: ["game engine"], categories: ["ide"], legacyViews: 8189 },
  { repo: "google-calendar", title: "Google Calendar", icon: "used/pack-10/015-halloween.svg", synonyms: ["calendar"], categories: ["service"], legacyViews: 0 },
  { repo: "google-chrome", title: "Chrome", icon: "used/pack-10/007-pumpkins.svg", synonyms: ["google", "chromium", "web browser"], categories: ["browser"], legacyViews: 96243 },
  { repo: "google-search", title: "Google Search", icon: "used/pack-2/023-crown.svg", synonyms: ["search engine"], categories: ["service"], legacyViews: 0 },
  { repo: "grep", title: "grep", icon: "used/pack-10/021-devil.svg", synonyms: ["search", "text search"], categories: ["terminal"], legacyViews: 0 },
  { repo: "grub", title: "GRUB", icon: "used/pack-9/045-spider.svg", platform: ["linux"], synonyms: ["bootloader"], categories: ["other"], legacyViews: 7947 },
  { repo: "gtk", title: "GTK", icon: "used/pack-5/008-wizard.svg", platform: ["linux"], synonyms: ["toolkit", "gui"], categories: ["other"], legacyViews: 111125 },
  { repo: "gtksourceview", title: "GtkSourceView", icon: "used/pack-6/016-cross.svg", platform: ["linux"], synonyms: ["gtk", "text widget"], categories: ["other"], legacyViews: 0 },
  { repo: "hacker-news", title: "Hacker News", icon: "used/pack-8/021-satellite.svg", synonyms: ["hn", "news"], categories: ["service"], legacyViews: 477 },
  { repo: "harpy-for-twitter", title: "Harpy for Twitter", icon: "used/pack-4/008-griffin.svg", synonyms: ["twitter"], categories: ["social"], legacyViews: 4 },
  { repo: "heroic-games-launcher", title: "Heroic Games Launcher", icon: "used/pack-2/017-arcade.svg", synonyms: ["epic", "gog", "gaming"], categories: ["other"], legacyViews: 0 },
  { repo: "highlightjs", title: "Highlight.js", icon: "used/pack-6/032-graveyard.svg", synonyms: ["syntax highlighting"], categories: ["other"], legacyViews: 19432 },
  { repo: "homepage-app", title: "Homepage", icon: "used/pack-3/011-magician-hat.svg", synonyms: ["dashboard"], categories: ["service"], legacyViews: 0 },
  { repo: "homer", title: "Homer", icon: "used/pack-10/029-candies.svg", synonyms: ["dashboard"], categories: ["service"], legacyViews: 1503 },
  { repo: "hyper", title: "Hyper", icon: "used/pack-1/025-candle-1.svg", synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 81376 },
  { repo: "hyprland", title: "Hyprland", icon: "used/pack-13/015-eye ball.svg", platform: ["linux"], synonyms: ["wayland", "compositor", "window manager"], categories: ["other"], legacyViews: 0 },
  { repo: "i3", title: "i3", icon: "used/pack-1/016-candies-1.svg", platform: ["linux"], synonyms: ["i3wm", "window manager", "tiling"], categories: ["other"], legacyViews: 22389 },
  { repo: "i3lock-color", title: "i3lock-color", icon: "used/pack-5/022-padlock.svg", platform: ["linux"], synonyms: ["lock screen", "i3"], categories: ["other"], legacyViews: 218 },
  { repo: "ida", title: "IDA Pro", icon: "used/pack-7/018-cleaver.svg", synonyms: ["reverse engineering", "disassembler"], categories: ["other"], legacyViews: 4300 },
  { repo: "idle", title: "IDLE", icon: "used/pack-5/042-handcuffs.svg", synonyms: ["python", "ide"], categories: ["ide"], legacyViews: 8443 },
  { repo: "imageglass", title: "ImageGlass", icon: "used/pack-10/032-crystal.svg", platform: ["windows"], synonyms: ["image viewer"], categories: ["other"], legacyViews: 650 },
  { repo: "infinity-for-reddit", title: "Infinity for Reddit", icon: "used/pack-8/016-galaxy.svg", synonyms: ["reddit"], categories: ["social"], legacyViews: 7 },
  { repo: "inkscape", title: "Inkscape", icon: "used/pack-7/030-skull.svg", synonyms: ["vector", "svg", "illustrator"], categories: ["other"], legacyViews: 2818 },
  { repo: "insomnia", title: "Insomnia", icon: "used/pack-1/043-scythe.svg", synonyms: ["rest", "api", "http client", "postman"], categories: ["other"], legacyViews: 25560 },
  { repo: "ish", title: "iSH", icon: "used/pack-6/031-broken.svg", synonyms: ["linux", "alpine"], categories: ["terminal"], legacyViews: 0 },
  { repo: "iterm", title: "iTerm", icon: "used/pack-7/042-haunted house.svg", platform: ["macos"], synonyms: ["iterm2", "terminal"], categories: ["terminal"], legacyViews: 359069 },
  { repo: "itfy", title: "ITFY", icon: "used/pack-10/040-skeleton.svg", synonyms: ["search"], categories: ["service"], legacyViews: 273 },
  { repo: "jabref", title: "Jabref", icon: "used/pack-1/022-witch.svg", synonyms: ["bibtex", "citation"], categories: ["other"], legacyViews: 0 },
  { repo: "javadoc", title: "Javadoc", icon: "used/pack-2/043-sword.svg", synonyms: ["java", "documentation"], categories: ["other"], legacyViews: 2947 },
  { repo: "jdownloader2", title: "JDownloader2", icon: "used/pack-3/001-fairy-dust.svg", synonyms: ["downloader"], categories: ["other"], legacyViews: 1324 },
  { repo: "jellyfin", title: "Jellyfin", icon: "used/pack-2/035-game controller.svg", synonyms: ["media server", "plex"], categories: ["service"], legacyViews: 0 },
  { repo: "jetbrains", title: "JetBrains", icon: "used/pack-1/046-zombie.svg", synonyms: ["intellij", "pycharm", "webstorm", "phpstorm", "rider", "clion", "datagrip", "rubymine", "appcode", "goland"], categories: ["ide"], legacyViews: 156545 },
  { repo: "jgrasp", title: "jGrasp", icon: "used/pack-1/007-guillotine.svg", synonyms: ["java", "ide"], categories: ["ide"], legacyViews: 5084 },
  { repo: "joplin", title: "Joplin", icon: "used/pack-10/006-coffin.svg", synonyms: ["notes", "markdown", "evernote"], categories: ["other"], legacyViews: 786 },
  { repo: "jupyter-notebook", title: "Jupyter Notebook", icon: "used/pack-11/037-alien.svg", synonyms: ["jupyter", "python", "notebook"], categories: ["ide"], legacyViews: 0 },
  { repo: "jupyterlab", title: "JupyterLab", icon: "used/pack-6/012-candles.svg", synonyms: ["jupyter", "python", "notebook"], categories: ["ide"], legacyViews: 13539 },
  { repo: "kakoune", title: "Kakoune", icon: "used/pack-1/033-black-cat.svg", synonyms: ["text editor", "vim"], categories: ["editor"], legacyViews: 1870 },
  { repo: "kanbanflow", title: "KanbanFlow", icon: "used/pack-9/038-candy-corn.svg", synonyms: ["kanban", "productivity"], categories: ["service"], legacyViews: 141 },
  { repo: "kate", title: "Kate", icon: "used/pack-5/033-smoke.svg", synonyms: ["text editor", "kde"], categories: ["editor"], legacyViews: 15371 },
  { repo: "kdiff3", title: "KDiff3", icon: "used/pack-10/047-gate.svg", synonyms: ["diff", "merge", "kde"], categories: ["other"], legacyViews: 1507 },
  { repo: "keybr", title: "Keybr", icon: "used/pack-5/048-handcuff.svg", synonyms: ["typing", "keyboard"], categories: ["service"], legacyViews: 0 },
  { repo: "keypirinha", title: "Keypirinha", icon: "used/pack-1/004-fear.svg", platform: ["windows"], synonyms: ["launcher"], categories: ["other"], legacyViews: 1143 },
  { repo: "kicad", title: "KiCad", icon: "used/pack-7/015-witch-hat.svg", synonyms: ["pcb", "eda", "electronics"], categories: ["other"], legacyViews: 3376 },
  { repo: "kitty", title: "Kitty", icon: "used/pack-1/015-makeup.svg", synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 14047 },
  { repo: "konsole", title: "Konsole", icon: "used/pack-3/035-potion-1.svg", platform: ["linux"], synonyms: ["kde", "terminal"], categories: ["terminal"], legacyViews: 40856 },
  { repo: "kristall", title: "Kristall", icon: "used/pack-5/018-magic wand.svg", synonyms: ["gemini", "browser"], categories: ["other"], legacyViews: 0 },
  { repo: "krita", title: "Krita", icon: "used/pack-10/028-poison.svg", synonyms: ["digital painting", "drawing"], categories: ["other"], legacyViews: 1179 },
  { repo: "kurozora", title: "Kurozora", icon: "used/pack-13/003-pumpkin.svg", synonyms: ["anime", "manga"], categories: ["other"], legacyViews: 0 },
  { repo: "labplot", title: "LabPlot", icon: "used/pack-8/033-planet.svg", synonyms: ["plotting", "data visualization"], categories: ["other"], legacyViews: 0 },
  { repo: "latex", title: "LaTeX", icon: "used/pack-9/023-pumpkin.svg", synonyms: ["tex", "document"], categories: ["other"], legacyViews: 3401 },
  { repo: "lazygit", title: "LazyGit", icon: "used/pack-2/042-winner.svg", synonyms: ["git", "tui"], categories: ["terminal"], legacyViews: 0 },
  { repo: "lcd-smartie", title: "LCD Smartie", icon: "used/pack-9/031-blood-transfusion.svg", platform: ["windows"], synonyms: ["lcd display"], categories: ["other"], legacyViews: 0 },
  { repo: "leetcode", title: "LeetCode", icon: "used/pack-4/021-torch.svg", synonyms: ["coding challenge", "algorithms"], categories: ["service"], legacyViews: 0 },
  { repo: "leftwm", title: "leftwm", icon: "used/pack-5/021-magic trick.svg", platform: ["linux"], synonyms: ["window manager", "tiling"], categories: ["other"], legacyViews: 163 },
  { repo: "libreddit", title: "Libreddit", icon: "used/pack-4/025-amphora.svg", synonyms: ["reddit"], categories: ["service"], legacyViews: 0 },
  { repo: "libreoffice", title: "LibreOffice", icon: "used/pack-7/010-spellbook.svg", synonyms: ["office", "writer", "calc"], categories: ["other"], legacyViews: 9430 },
  { repo: "lichess", title: "Lichess", icon: "used/pack-2/032-chess.svg", synonyms: ["chess"], categories: ["service"], legacyViews: 0 },
  { repo: "light-table", title: "Light Table", icon: "used/pack-1/050-pumpkin.svg", synonyms: ["code editor"], categories: ["editor"], legacyViews: 7871 },
  { repo: "lightpaper", title: "LightPaper", icon: "used/pack-5/030-voodoo.svg", platform: ["macos"], synonyms: ["markdown", "text editor"], categories: ["editor"], legacyViews: 3638 },
  { repo: "limechat", title: "LimeChat", icon: "used/pack-3/016-fire.svg", platform: ["macos"], synonyms: ["irc", "chat"], categories: ["social"], legacyViews: 1142 },
  { repo: "linear", title: "Linear", icon: "used/pack-8/015-planet.svg", synonyms: ["project management", "issue tracking"], categories: ["service"], legacyViews: 1286 },
  { repo: "liteide", title: "LiteIDE", icon: "used/pack-7/041-spider.svg", synonyms: ["go", "golang", "ide"], categories: ["ide"], legacyViews: 1283 },
  { repo: "lnav", title: "lnav", icon: "used/pack-2/001-billiard.svg", synonyms: ["log viewer"], categories: ["terminal"], legacyViews: 0 },
  { repo: "logseq", title: "Logseq", icon: "used/pack-8/032-constellation.svg", synonyms: ["notes", "knowledge base", "roam"], categories: ["other"], legacyViews: 4207 },
  { repo: "lsd", title: "lsd", icon: "used/pack-13/025-fairy.svg", synonyms: ["ls"], categories: ["terminal"], legacyViews: 0 },
  { repo: "ltspice", title: "LTSpice", icon: "used/pack-7/048-coffin.svg", platform: ["windows"], synonyms: ["spice", "circuit simulator"], categories: ["other"], legacyViews: 1004 },
  { repo: "lxterminal", title: "LXTerminal", icon: "used/pack-10/039-balloon.svg", platform: ["linux"], synonyms: ["lxde", "terminal"], categories: ["terminal"], legacyViews: 1397 },
  { repo: "m8", title: "Dirtywave M8", icon: "used/pack-2/031-gameboy.svg", synonyms: ["tracker", "music", "synthesizer"], categories: ["other"], legacyViews: 0 },
  { repo: "macdown", title: "MacDown", icon: "used/pack-1/042-candle.svg", platform: ["macos"], synonyms: ["markdown", "editor"], categories: ["editor"], legacyViews: 7540 },
  { repo: "macos-color-picker", title: "macOS Color Picker", icon: "used/pack-3/010-crystal.svg", platform: ["macos"], synonyms: ["color picker", "eyedropper"], categories: ["other"], legacyViews: 1131 },
  { repo: "mailspring", title: "Mailspring", icon: "used/pack-7/009-owl.svg", synonyms: ["email", "mail client"], categories: ["other"], legacyViews: 5848 },
  { repo: "makehuman", title: "Makehuman", icon: "used/pack-3/026-spell.svg", synonyms: ["3d", "modeling"], categories: ["other"], legacyViews: 0 },
  { repo: "mako", title: "Mako", icon: "used/pack-13/010-coffin.svg", platform: ["linux"], synonyms: ["notification", "wayland"], categories: ["other"], legacyViews: 591 },
  { repo: "man-pages", title: "man-pages", icon: "used/pack-10/043-prisoner.svg", platform: ["linux"], synonyms: ["manual", "documentation"], categories: ["terminal"], legacyViews: 0 },
  { repo: "mantine", title: "Mantine", icon: "used/pack-3/014-fairy.svg", synonyms: ["react", "ui", "components"], categories: ["other"], legacyViews: 0 },
  { repo: "marp", title: "Marp", icon: "used/pack-7/036-party.svg", synonyms: ["markdown", "presentation"], categories: ["other"], legacyViews: 3314 },
  { repo: "matlab", title: "MATLAB", icon: "used/pack-7/049-grim-reaper.svg", synonyms: ["mathematics", "simulation"], categories: ["ide"], legacyViews: 5296 },
  { repo: "matplotlib", title: "Matplotlib", icon: "used/pack-7/021-frankenstein.svg", synonyms: ["python", "plotting", "visualization"], categories: ["other"], legacyViews: 2171 },
  { repo: "mattermost", title: "Mattermost", icon: "used/pack-1/019-spider.svg", synonyms: ["chat", "slack"], categories: ["social"], legacyViews: 4649 },
  { repo: "metaeditor", title: "MetaEditor", icon: "used/pack-10/035-gift.svg", platform: ["windows"], synonyms: ["trading", "mql"], categories: ["editor"], legacyViews: 1324 },
  { repo: "metatrader5", title: "MetaTrader 5", icon: "used/pack-9/036-witch-hat.svg", synonyms: ["trading", "forex", "mt5"], categories: ["other"], legacyViews: 3090 },
  { repo: "micro", title: "Micro", icon: "used/pack-3/019-lantern.svg", synonyms: ["text editor", "terminal"], categories: ["terminal"], legacyViews: 2415 },
  { repo: "microsoft-edge", title: "Microsoft Edge", icon: "used/pack-13/027-ghost.svg", synonyms: ["edge", "chromium", "web browser"], categories: ["browser"], legacyViews: 0 },
  { repo: "midnight-commander", title: "Midnight Commander", icon: "used/pack-3/030-moon.svg", synonyms: ["mc", "file manager"], categories: ["terminal"], legacyViews: 8139 },
  { repo: "mindnode", title: "MindNode", icon: "used/pack-5/007-magic-mirror.svg", platform: ["macos"], synonyms: ["mind map", "brainstorm"], categories: ["other"], legacyViews: 5614 },
  { repo: "minecraft", title: "Minecraft", icon: "used/pack-2/045-computer game.svg", synonyms: ["game"], categories: ["other"], legacyViews: 604 },
  { repo: "mintty", title: "Mintty", icon: "used/pack-1/014-voodoo-doll.svg", platform: ["windows"], synonyms: ["terminal", "cygwin"], categories: ["terminal"], legacyViews: 22290 },
  { repo: "misskey", title: "Misskey", icon: "used/pack-4/009-hephaestus-1.svg", synonyms: ["mastodon", "fediverse"], categories: ["social"], legacyViews: 0 },
  { repo: "mixplorer", title: "MiXplorer", icon: "used/pack-9/029-spellbook.svg", synonyms: ["file manager", "android"], categories: ["other"], legacyViews: 1520 },
  { repo: "mkdocs", title: "MkDocs", icon: "used/pack-13/043-bible.svg", synonyms: ["documentation", "markdown"], categories: ["other"], legacyViews: 0 },
  { repo: "mobaxterm", title: "MobaXterm", icon: "used/pack-3/042-skull.svg", platform: ["windows"], synonyms: ["terminal", "ssh", "x11"], categories: ["terminal"], legacyViews: 15362 },
  { repo: "monkeytype", title: "Monkeytype", icon: "used/pack-10/004-mummy.svg", synonyms: ["typing", "keyboard"], categories: ["service"], legacyViews: 890 },
  { repo: "monodevelop", title: "MonoDevelop", icon: "used/pack-1/027-hand.svg", synonyms: ["c#", "dotnet", ".net"], categories: ["ide"], legacyViews: 13587 },
  { repo: "mousepad", title: "Mousepad", icon: "used/pack-2/022-mouse.svg", platform: ["linux"], synonyms: ["text editor", "xfce"], categories: ["editor"], legacyViews: 7044 },
  { repo: "musicbee", title: "MusicBee", icon: "used/pack-3/022-magic.svg", platform: ["windows"], synonyms: ["music player"], categories: ["other"], legacyViews: 1757 },
  { repo: "musikcube", title: "musikcube", icon: "used/pack-9/020-bomb.svg", synonyms: ["music player"], categories: ["terminal"], legacyViews: 399 },
  { repo: "mutt", title: "Mutt", icon: "used/pack-3/045-tree.svg", synonyms: ["email", "mail client"], categories: ["terminal"], legacyViews: 10013 },
  { repo: "mysql-workbench", title: "MySQL Workbench", icon: "used/pack-9/040-scarecrow.svg", synonyms: ["mysql", "database", "sql"], categories: ["ide"], legacyViews: 8728 },
  { repo: "ncspot", title: "ncspot", icon: "used/pack-7/039-tombstone.svg", synonyms: ["spotify", "music player"], categories: ["terminal"], legacyViews: 837 },
  { repo: "netbeans", title: "Netbeans", icon: "used/pack-7/017-scarecrow.svg", synonyms: ["java", "ide"], categories: ["ide"], legacyViews: 126987 },
  { repo: "new-tabs", title: "New Tabs", icon: "used/pack-5/017-magician hat.svg", synonyms: ["browser extension"], categories: ["other"], legacyViews: 9 },
  { repo: "newsboat", title: "Newsboat", icon: "used/pack-7/047-vampire.svg", synonyms: ["rss", "feed reader"], categories: ["terminal"], legacyViews: 0 },
  { repo: "NewTerm2", title: "NewTerm2", icon: "used/pack-7/026-mask.svg", synonyms: ["ios"], categories: ["terminal"], legacyViews: 0 },
  { repo: "nextcloud", title: "Nextcloud", icon: "used/pack-2/044-podium.svg", synonyms: ["cloud storage", "owncloud"], categories: ["service"], legacyViews: 566 },
  { repo: "ngenuity", title: "HyperX NGNUITY", icon: "used/pack-3/018-key.svg", platform: ["windows"], synonyms: ["hyperx", "keyboard", "rgb"], categories: ["other"], legacyViews: 605 },
  { repo: "nilesoft-shell", title: "Nilesoft Shell", icon: "used/pack-2/016-game controller.svg", platform: ["windows"], synonyms: ["context menu"], categories: ["other"], legacyViews: 0 },
  { repo: "nitter", title: "Nitter", icon: "used/pack-4/007-owl.svg", synonyms: ["twitter"], categories: ["service"], legacyViews: 8 },
  { repo: "nnn", title: "nnn", icon: "used/pack-3/050-wand.svg", synonyms: ["file manager"], categories: ["terminal"], legacyViews: 0 },
  { repo: "node-console", title: "Node Console", icon: "used/pack-9/025-owl.svg", synonyms: ["nodejs", "node", "repl"], categories: ["terminal"], legacyViews: 1150 },
  { repo: "noir", title: "Noir", icon: "used/pack-8/036-eclipse.svg", platform: ["macos"], synonyms: ["dark mode", "safari"], categories: ["other"], legacyViews: 394 },
  { repo: "notepad-plus-plus", title: "Notepad++", icon: "used/pack-7/002-ghosts.svg", platform: ["windows"], synonyms: ["notepad", "text editor", "npp"], categories: ["editor"], legacyViews: 862543 },
  { repo: "notesnook", title: "Notesnook", icon: "used/pack-9/004-werewolf.svg", synonyms: ["notes", "encrypted"], categories: ["other"], legacyViews: 0 },
  { repo: "nova-launcher", title: "Nova Launcher", icon: "used/pack-9/003-witch.svg", synonyms: ["android", "launcher"], categories: ["other"], legacyViews: 1945 },
  { repo: "nova", title: "Nova", icon: "used/pack-8/037-meteor.svg", platform: ["macos"], synonyms: ["text editor", "panic"], categories: ["editor"], legacyViews: 1728 },
  { repo: "novel-writer", title: "novelWriter", icon: "used/pack-5/043-stage.svg", synonyms: ["writing", "novel"], categories: ["other"], legacyViews: 137 },
  { repo: "nylas-n1", title: "Nylas N1", icon: "used/pack-5/045-hourglass.svg", synonyms: ["email", "mail client"], categories: ["other"], legacyViews: 4077 },
  { repo: "nyxt", title: "Nyxt", icon: "used/pack-9/047-cauldron.svg", platform: ["linux", "macos"], synonyms: ["browser", "keyboard-driven"], categories: ["browser"], legacyViews: 727 },
  { repo: "obsidian", title: "Obsidian", icon: "used/pack-5/036-gemstone.svg", synonyms: ["notes", "knowledge base", "markdown", "roam"], categories: ["other"], legacyViews: 11084 },
  { repo: "oh-my-posh", title: "Oh My Posh", icon: "used/pack-7/046-zombie.svg", synonyms: ["prompt", "powerline"], categories: ["terminal"], legacyViews: 4106 },
  { repo: "omarchy", title: "Omarchy", icon: "used/pack-8/017-sun.svg", platform: ["linux"], synonyms: ["window manager"], categories: ["other"], legacyViews: 0 },
  { repo: "omglol", title: "omg.lol", icon: "used/pack-4/001-zeus.svg", synonyms: ["email", "url shortener"], categories: ["service"], legacyViews: 199 },
  { repo: "onecommander", title: "OneCommander", icon: "used/pack-10/008-cemetery.svg", platform: ["windows"], synonyms: ["file manager"], categories: ["other"], legacyViews: 0 },
  { repo: "openbox", title: "Openbox", icon: "used/pack-2/041-box.svg", platform: ["linux"], synonyms: ["window manager"], categories: ["other"], legacyViews: 1205 },
  { repo: "opencode", title: "OpenCode", icon: "used/pack-8/003-earth.svg", synonyms: ["open source"], categories: ["service"], legacyViews: 0 },
  { repo: "openscad", title: "OpenSCAD", icon: "used/pack-8/044-rocket.svg", synonyms: ["3d", "cad"], categories: ["other"], legacyViews: 0 },
  { repo: "oracle-sql-developer", title: "Oracle SQL Developer", icon: "used/pack-1/029-werewolf.svg", synonyms: ["oracle", "database", "sql"], categories: ["ide"], legacyViews: 73678 },
  { repo: "p10k-oh-my-posh", title: "Powerlevel10k for Oh My Posh", icon: "used/pack-8/048-satellite.svg", synonyms: ["powerlevel10k", "p10k", "prompt"], categories: ["terminal"], legacyViews: 0 },
  { repo: "pandoc", title: "Pandoc", icon: "used/pack-9/035-black-cat.svg", synonyms: ["document converter", "markdown"], categories: ["terminal"], legacyViews: 1387 },
  { repo: "pantheon-terminal", title: "Pantheon Terminal", icon: "used/pack-9/041-torch.svg", platform: ["linux"], synonyms: ["elementary", "terminal"], categories: ["terminal"], legacyViews: 824 },
  { repo: "papirus-folders", title: "Papirus Folders", icon: "used/pack-3/005-candle.svg", platform: ["linux"], synonyms: ["icon theme", "papirus"], categories: ["other"], legacyViews: 0 },
  { repo: "passky", title: "Passky", icon: "used/pack-9/012-skull.svg", synonyms: ["password manager"], categories: ["other"], legacyViews: 452 },
  { repo: "peacock-extension", title: "Peacock Extension", icon: "used/pack-4/005-dove.svg", synonyms: ["vscode"], categories: ["other"], legacyViews: 109 },
  { repo: "plank", title: "Plank", icon: "used/pack-4/029-trireme.svg", platform: ["linux"], synonyms: ["dock", "launcher"], categories: ["other"], legacyViews: 3329 },
  { repo: "plsql-developer", title: "PL/SQL Developer", icon: "used/pack-10/026-pirate.svg", platform: ["windows"], synonyms: ["oracle", "plsql", "database"], categories: ["ide"], legacyViews: 167 },
  { repo: "plymouth", title: "Plymouth", icon: "used/pack-13/039-dessert.svg", platform: ["linux"], synonyms: ["boot screen", "splash screen"], categories: ["other"], legacyViews: 0 },
  { repo: "polybar", title: "Polybar", icon: "used/pack-12/017-aphrodite.svg", platform: ["linux"], synonyms: ["status bar", "bar"], categories: ["other"], legacyViews: 0 },
  { repo: "polymc", title: "PolyMC", icon: "used/pack-2/024-hearts.svg", synonyms: ["minecraft", "launcher"], categories: ["other"], legacyViews: 221 },
  { repo: "postbox", title: "Postbox", icon: "used/pack-4/038-hermes-2.svg", synonyms: ["email", "mail client"], categories: ["other"], legacyViews: 543 },
  { repo: "powerlevel10k", title: "Powerlevel10k", icon: "used/pack-9/016-hook.svg", synonyms: ["p10k", "zsh", "prompt", "theme"], categories: ["terminal"], legacyViews: 4912 },
  { repo: "powershell-ise", title: "PowerShell ISE", icon: "used/pack-3/040-sandglass.svg", platform: ["windows"], synonyms: ["powershell"], categories: ["terminal"], legacyViews: 0 },
  { repo: "powershell", title: "PowerShell", icon: "used/pack-5/046-magic trick.svg", synonyms: ["pwsh"], categories: ["terminal"], legacyViews: 66911 },
  { repo: "prism", title: "Prism", icon: "used/pack-3/034-pot.svg", synonyms: ["syntax highlighting"], categories: ["other"], legacyViews: 3893 },
  { repo: "prompt", title: "Prompt", icon: "used/pack-13/046-night.svg", platform: ["macos"], synonyms: ["ssh", "terminal"], categories: ["terminal"], legacyViews: 0 },
  { repo: "protonmail", title: "Protonmail", icon: "used/pack-2/028-glove.svg", synonyms: ["email", "encrypted"], categories: ["service"], legacyViews: 0 },
  { repo: "psychopy", title: "PsychoPy", icon: "used/pack-10/049-serial-killer.svg", synonyms: ["psychology", "experiment"], categories: ["other"], legacyViews: 329 },
  { repo: "pygments", title: "Pygments", icon: "used/pack-1/039-ghost.svg", synonyms: ["syntax highlighting", "python"], categories: ["other"], legacyViews: 7032 },
  { repo: "pythonista", title: "Pythonista", icon: "used/pack-6/048-grave.svg", synonyms: ["python", "ios"], categories: ["ide"], legacyViews: 11018 },
  { repo: "pywal", title: "Pywal", icon: "used/pack-5/005-magic-broom.svg", synonyms: ["color scheme", "wallpaper"], categories: ["other"], legacyViews: 1347 },
  { repo: "qbittorrent", title: "QBittorrent", icon: "used/pack-10/010-candle.svg", synonyms: ["torrent", "bittorrent"], categories: ["other"], legacyViews: 79666 },
  { repo: "qt5", title: "qt5", icon: "used/pack-7/043-candles.svg", synonyms: ["qt", "framework", "gui"], categories: ["other"], legacyViews: 5029 },
  { repo: "qtcreator", title: "Qt Creator", icon: "used/pack-5/024-cauldron.svg", synonyms: ["qt", "ide", "c++"], categories: ["ide"], legacyViews: 51366 },
  { repo: "qterminal", title: "Qterminal", icon: "used/pack-9/046-muffin.svg", platform: ["linux"], synonyms: ["terminal", "lxqt"], categories: ["terminal"], legacyViews: 0 },
  { repo: "quassel", title: "Quassel", icon: "used/pack-4/046-evil.svg", synonyms: ["irc", "chat"], categories: ["social"], legacyViews: 3861 },
  { repo: "quiver", title: "Quiver", icon: "used/pack-5/041-guillotine.svg", platform: ["macos"], synonyms: ["notes", "programmer notebook"], categories: ["other"], legacyViews: 4489 },
  { repo: "qutebrowser", title: "Qutebrowser", icon: "used/pack-5/015-box.svg", synonyms: ["web browser", "keyboard-driven", "vim"], categories: ["browser"], legacyViews: 7550 },
  { repo: "ranger", title: "ranger", icon: "used/pack-9/019-brain.svg", synonyms: ["file manager"], categories: ["terminal"], legacyViews: 2664 },
  { repo: "raycast", title: "Raycast", icon: "used/pack-8/027-satellite.svg", platform: ["macos"], synonyms: ["launcher", "spotlight", "alfred"], categories: ["other"], legacyViews: 0 },
  { repo: "readwise-reader", title: "Readwise Reader", icon: "used/pack-8/030-books.svg", synonyms: ["readwise", "reader"], categories: ["service"], legacyViews: 0 },
  { repo: "renoise", title: "ReNoise", icon: "used/pack-8/047-computer.svg", synonyms: ["music", "tracker", "daw"], categories: ["other"], legacyViews: 1683 },
  { repo: "replugged", title: "Replugged", icon: "used/pack-2/025-tetris.svg", synonyms: ["discord"], categories: ["other"], legacyViews: 0 },
  { repo: "revolt", title: "Revolt", icon: "used/pack-9/030-coffin.svg", synonyms: ["chat", "discord"], categories: ["social"], legacyViews: 454 },
  { repo: "revolution-irc", title: "Revolution IRC", icon: "used/pack-9/008-trident.svg", synonyms: ["irc", "chat", "android"], categories: ["social"], legacyViews: 319 },
  { repo: "rime", title: "Rime", icon: "used/pack-2/037-gaming.svg", synonyms: ["input method", "chinese"], categories: ["other"], legacyViews: 0 },
  { repo: "rio-terminal", title: "Rio Terminal", icon: "used/pack-12/028-kraken.svg", synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 0 },
  { repo: "ripcord", title: "Ripcord", icon: "used/pack-10/042-knife.svg", synonyms: ["discord", "slack", "chat"], categories: ["social"], legacyViews: 969 },
  { repo: "ripgrep", title: "ripgrep", icon: "used/pack-10/017-witch-1.svg", synonyms: ["rg", "grep", "search"], categories: ["terminal"], legacyViews: 0 },
  { repo: "roam-research", title: "Roam Research", icon: "used/pack-5/050-circle.svg", synonyms: ["notes", "knowledge base"], categories: ["service"], legacyViews: 4366 },
  { repo: "rofi", title: "rofi", icon: "used/pack-7/028-lollipop.svg", platform: ["linux"], synonyms: ["launcher", "dmenu"], categories: ["other"], legacyViews: 13546 },
  { repo: "rstudio", title: "RStudio", icon: "used/pack-9/014-living-dead.svg", synonyms: ["r", "ide", "statistics"], categories: ["ide"], legacyViews: 3300 },
  { repo: "runjs", title: "RunJs", icon: "used/pack-4/030-chariot.svg", synonyms: ["javascript", "playground"], categories: ["other"], legacyViews: 89 },
  { repo: "sandpack", title: "Sandpack", icon: "used/pack-3/007-castle.svg", synonyms: ["codesandbox", "code editor"], categories: ["other"], legacyViews: 193 },
  { repo: "scrivener", title: "Scrivener", icon: "used/pack-3/015-feather.svg", synonyms: ["writing", "novel"], categories: ["other"], legacyViews: 328 },
  { repo: "sequel-ace", title: "Sequel Ace", icon: "used/pack-9/001-moon.svg", platform: ["macos"], synonyms: ["mysql", "database", "sequel pro"], categories: ["other"], legacyViews: 538 },
  { repo: "sequel-pro", title: "Sequel Pro", icon: "used/pack-5/012-spell book.svg", platform: ["macos"], synonyms: ["mysql", "database"], categories: ["other"], legacyViews: 15860 },
  { repo: "serenityos", title: "SerenityOS", icon: "used/pack-8/014-galaxy.svg", synonyms: ["operating system", "os"], categories: ["other"], legacyViews: 532 },
  { repo: "sidenotes", title: "SideNotes", icon: "used/pack-9/050-knife.svg", platform: ["macos"], synonyms: ["notes"], categories: ["other"], legacyViews: 1151 },
  { repo: "sioyek", title: "Sioyek", icon: "used/pack-5/023-mask.svg", synonyms: ["pdf", "viewer"], categories: ["other"], legacyViews: 152 },
  { repo: "sketch", title: "Sketch", icon: "used/pack-3/025-magic-wand-1.svg", platform: ["macos"], synonyms: ["design", "ui", "ux"], categories: ["other"], legacyViews: 2350 },
  { repo: "slack", title: "Slack", icon: "used/pack-1/047-cleaver.svg", synonyms: ["chat", "messaging"], categories: ["social"], legacyViews: 114299 },
  { repo: "smartgit", title: "SmartGit", icon: "used/pack-8/026-alien.svg", synonyms: ["git", "gui"], categories: ["other"], legacyViews: 0 },
  { repo: "snappy-driver-installer", title: "Snappy Driver Installer", icon: "used/pack-2/019-console.svg", platform: ["windows"], synonyms: ["driver", "installer"], categories: ["other"], legacyViews: 0 },
  { repo: "sniffnet", title: "Sniffnet", icon: "used/pack-3/029-enchanted-mirror.svg", synonyms: ["network", "sniffer", "monitor"], categories: ["other"], legacyViews: 0 },
  { repo: "snippetslab", title: "SnippetsLab", icon: "used/pack-5/037-powder.svg", platform: ["macos"], synonyms: ["snippets", "code"], categories: ["other"], legacyViews: 328 },
  { repo: "solidworks", title: "SolidWorks", icon: "used/pack-10/044-monster-1.svg", platform: ["windows"], synonyms: ["cad", "3d"], categories: ["other"], legacyViews: 980 },
  { repo: "spacemacs", title: "Spacemacs", icon: "used/pack-8/018-planet.svg", synonyms: ["emacs", "vim"], categories: ["editor"], legacyViews: 3094 },
  { repo: "speedcrunch", title: "SpeedCrunch", icon: "used/pack-2/005-slot machine.svg", synonyms: ["calculator"], categories: ["other"], legacyViews: 0 },
  { repo: "spicetify", title: "Spicetify", icon: "used/pack-4/020-mandolin.svg", synonyms: ["spotify", "customization"], categories: ["other"], legacyViews: 478 },
  { repo: "spotify-tui", title: "Spotify TUI", icon: "used/pack-7/031-sweets.svg", synonyms: ["spotify", "music player"], categories: ["terminal"], legacyViews: 9993 },
  { repo: "spyder-ide", title: "Spyder IDE", icon: "used/pack-10/002-spider.svg", synonyms: ["python", "ide"], categories: ["ide"], legacyViews: 1739 },
  { repo: "st", title: "st", icon: "used/pack-13/042-halloween.svg", platform: ["linux"], synonyms: ["simple terminal", "suckless", "terminal"], categories: ["terminal"], legacyViews: 0 },
  { repo: "stackoverflow", title: "StackOverflow", icon: "used/pack-5/026-candlestick.svg", synonyms: ["stack overflow", "programming", "qa"], categories: ["service"], legacyViews: 2151 },
  { repo: "standard-notes", title: "Standard Notes", icon: "used/pack-7/016-eyeball.svg", synonyms: ["notes", "encrypted"], categories: ["other"], legacyViews: 3419 },
  { repo: "starship", title: "Starship", icon: "used/pack-8/041-spaceship.svg", synonyms: ["prompt", "shell"], categories: ["terminal"], legacyViews: 3169 },
  { repo: "steam", title: "Steam", icon: "used/pack-5/049-target.svg", synonyms: ["gaming", "games"], categories: ["other"], legacyViews: 27555 },
  { repo: "stirling-pdf", title: "Stirling PDF", icon: "used/pack-3/028-mass.svg", synonyms: ["pdf", "editor"], categories: ["other"], legacyViews: 0 },
  { repo: "streamlit", title: "Streamlit", icon: "used/pack-10/025-monster.svg", synonyms: ["python", "data science", "web app"], categories: ["other"], legacyViews: 1852 },
  { repo: "sublime", title: "Sublime", icon: "used/pack-1/044-spider-web.svg", synonyms: ["sublime text", "text editor"], categories: ["editor"], legacyViews: 158632 },
  { repo: "subsonic", title: "Subsonic", icon: "used/pack-3/033-plant.svg", synonyms: ["music", "streaming"], categories: ["service"], legacyViews: 0 },
  { repo: "suckless-tabbed", title: "Suckless Tabbed", icon: "used/pack-9/007-zombie.svg", platform: ["linux"], synonyms: ["suckless", "tabs"], categories: ["other"], legacyViews: 82 },
  { repo: "sumatra-pdf", title: "Sumatra PDF", icon: "used/pack-10/013-frankenstein.svg", platform: ["windows"], synonyms: ["pdf", "viewer"], categories: ["other"], legacyViews: 2814 },
  { repo: "swaylock", title: "Swaylock", icon: "used/pack-2/027-shield.svg", platform: ["linux"], synonyms: ["lock screen", "wayland"], categories: ["other"], legacyViews: 0 },
  { repo: "swiftui", title: "SwiftUI", icon: "used/pack-10/031-wizard-1.svg", platform: ["macos"], synonyms: ["swift", "ui", "apple"], categories: ["other"], legacyViews: 1370 },
  { repo: "tableplus", title: "TablePlus", icon: "used/pack-13/045-halloween.svg", synonyms: ["database", "sql"], categories: ["other"], legacyViews: 0 },
  { repo: "tabletop-simulator", title: "Tabletop Simulator", icon: "used/pack-2/048-cards.svg", synonyms: ["board game", "game"], categories: ["other"], legacyViews: 3311 },
  { repo: "tailwind", title: "Tailwind", icon: "used/pack-10/034-moon.svg", synonyms: ["tailwind css", "css", "framework"], categories: ["other"], legacyViews: 4335 },
  { repo: "telegram-android", title: "Telegram Android", icon: "used/pack-6/038-skull.svg", synonyms: ["telegram", "messaging"], categories: ["social"], legacyViews: 13607 },
  { repo: "telegram-ios", title: "Telegram iOS", icon: "used/pack-7/006-skeleton.svg", synonyms: ["telegram", "messaging"], categories: ["social"], legacyViews: 6243 },
  { repo: "telegram", title: "Telegram", icon: "used/pack-4/036-hermes-1.svg", synonyms: ["messaging", "chat"], categories: ["social"], legacyViews: 111236 },
  { repo: "terminal-app", title: "Terminal.app", icon: "used/pack-1/035-cauldron.svg", platform: ["macos"], synonyms: ["terminal", "macos terminal"], categories: ["terminal"], legacyViews: 311241 },
  { repo: "terminator", title: "Terminator", icon: "used/pack-7/003-werewolf.svg", platform: ["linux", "macos"], synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 9352 },
  { repo: "termite", title: "Termite", icon: "used/pack-3/037-voodoo-doll.svg", platform: ["linux"], synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 3460 },
  { repo: "termux", title: "Termux", icon: "used/pack-7/022-mummy.svg", synonyms: ["terminal", "android"], categories: ["terminal"], legacyViews: 12761 },
  { repo: "texshop", title: "TeXShop", icon: "used/pack-9/022-ghost.svg", platform: ["macos"], synonyms: ["latex", "tex"], categories: ["other"], legacyViews: 638 },
  { repo: "texstudio", title: "TeXstudio", icon: "used/pack-10/045-jack-o-lantern.svg", synonyms: ["latex", "tex", "editor"], categories: ["editor"], legacyViews: 2357 },
  { repo: "textastic", title: "Textastic", icon: "used/pack-9/006-frankenstein.svg", platform: ["macos"], synonyms: ["text editor", "code editor"], categories: ["editor"], legacyViews: 427 },
  { repo: "textmate", title: "Textmate", icon: "used/pack-1/038-tombstone.svg", platform: ["macos"], synonyms: ["text editor"], categories: ["editor"], legacyViews: 12643 },
  { repo: "textual", title: "Textual", icon: "used/pack-1/032-bat.svg", platform: ["macos"], synonyms: ["irc", "chat"], categories: ["social"], legacyViews: 4338 },
  { repo: "texworks", title: "TeXworks", icon: "used/pack-10/019-skull.svg", synonyms: ["latex", "tex"], categories: ["editor"], legacyViews: 0 },
  { repo: "thelounge", title: "The Lounge", icon: "used/pack-7/012-dead-tree.svg", synonyms: ["irc", "chat", "web"], categories: ["social"], legacyViews: 1166 },
  { repo: "thonny", title: "Thonny", icon: "used/pack-4/042-hydra.svg", synonyms: ["python", "ide"], categories: ["ide"], legacyViews: 7258 },
  { repo: "thumb-key", title: "ThumbKey", icon: "used/pack-10/022-wizard.svg", synonyms: ["keyboard", "android"], categories: ["other"], legacyViews: 0 },
  { repo: "thunderbird", title: "Thunderbird", icon: "used/pack-4/003-phoenix.svg", synonyms: ["email", "mail client", "mozilla"], categories: ["other"], legacyViews: 4140 },
  { repo: "tiddlywiki", title: "TiddlyWiki", icon: "used/pack-5/035-tent.svg", synonyms: ["wiki", "notes"], categories: ["other"], legacyViews: 2821 },
  { repo: "tig", title: "tig", icon: "used/pack-10/011-cauldron.svg", synonyms: ["git", "tui"], categories: ["terminal"], legacyViews: 0 },
  { repo: "tilix", title: "Tilix", icon: "used/pack-2/046-ghost.svg", platform: ["linux"], synonyms: ["terminal", "gnome"], categories: ["terminal"], legacyViews: 7564 },
  { repo: "tint2", title: "tint2", icon: "used/pack-5/009-potion.svg", platform: ["linux"], synonyms: ["panel", "taskbar"], categories: ["other"], legacyViews: 465 },
  { repo: "tlrc", title: "tlrc", icon: "used/pack-3/049-vial.svg", synonyms: ["tldr", "man pages"], categories: ["terminal"], legacyViews: 0 },
  { repo: "tmux", title: "tmux", icon: "used/pack-1/030-clown.svg", platform: ["linux", "macos"], synonyms: ["terminal multiplexer"], categories: ["terminal"], legacyViews: 38512 },
  { repo: "todoist", title: "Todoist", icon: "used/pack-4/004-hephaestus.svg", synonyms: ["todo", "task manager"], categories: ["service"], legacyViews: 0 },
  { repo: "tofi", title: "Tofi", icon: "used/pack-12/021-werewolf.svg", platform: ["linux"], synonyms: ["launcher", "wayland"], categories: ["other"], legacyViews: 0 },
  { repo: "total-commander", title: "Total Commander", icon: "used/pack-3/044-spell-1.svg", platform: ["windows"], synonyms: ["file manager"], categories: ["other"], legacyViews: 4995 },
  { repo: "tower", title: "Tower", icon: "used/pack-8/025-observatory.svg", platform: ["macos", "windows"], synonyms: ["git", "gui"], categories: ["other"], legacyViews: 1151 },
  { repo: "tridactyl", title: "Tridactyl", icon: "used/pack-1/021-candy-corn.svg", synonyms: ["firefox", "vim", "browser extension"], categories: ["other"], legacyViews: 132 },
  { repo: "tty", title: "TTY", icon: "used/pack-10/023-living-dead.svg", platform: ["linux"], synonyms: ["virtual console", "terminal"], categories: ["terminal"], legacyViews: 2225 },
  { repo: "tumblr", title: "Tumblr", icon: "used/pack-13/001-vampire.svg", synonyms: ["social network", "blogging"], categories: ["social"], legacyViews: 0 },
  { repo: "tut", title: "tut", icon: "used/pack-3/036-rabbit.svg", synonyms: ["mastodon", "tui"], categories: ["terminal"], legacyViews: 0 },
  { repo: "tym", title: "tym", icon: "used/pack-9/002-crow.svg", platform: ["linux"], synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 368 },
  { repo: "typora", title: "Typora", icon: "used/pack-1/017-witch-1.svg", synonyms: ["markdown", "editor"], categories: ["editor"], legacyViews: 6540 },
  { repo: "ueli", title: "Ueli", icon: "used/pack-9/042-eye.svg", platform: ["macos", "windows"], synonyms: ["launcher", "spotlight"], categories: ["other"], legacyViews: 460 },
  { repo: "ulauncher", title: "Ulauncher", icon: "used/pack-7/005-candies.svg", platform: ["linux"], synonyms: ["launcher"], categories: ["other"], legacyViews: 5331 },
  { repo: "ulysses", title: "Ulysses", icon: "used/pack-3/027-magician-hat-1.svg", platform: ["macos"], synonyms: ["writing", "markdown"], categories: ["editor"], legacyViews: 7012 },
  { repo: "unigram", title: "Unigram", icon: "used/pack-7/040-jack-o-lantern.svg", platform: ["windows"], synonyms: ["telegram"], categories: ["social"], legacyViews: 677 },
  { repo: "unreal-engine", title: "Unreal Engine", icon: "used/pack-9/017-fangs.svg", synonyms: ["game engine", "ue4", "ue5"], categories: ["ide"], legacyViews: 1397 },
  { repo: "uptime-kuma", title: "Uptime Kuma", icon: "used/pack-10/036-werewolf.svg", synonyms: ["monitoring", "uptime"], categories: ["service"], legacyViews: 0 },
  { repo: "vesktop-discord", title: "Vesktop Discord", icon: "used/pack-11/043-robot.svg", synonyms: ["discord", "vencord", "vesktop"], categories: ["social"], legacyViews: 0 },
  { repo: "vim", title: "Vim", icon: "used/pack-1/040-zombie-1.svg", synonyms: ["neovim", "nvim", "gvim", "text editor"], categories: ["editor"], legacyViews: 312057 },
  { repo: "vimium", title: "Vimium", icon: "used/pack-3/013-chest-1.svg", synonyms: ["vim", "browser extension"], categories: ["other"], legacyViews: 6256 },
  { repo: "vis", title: "vis", icon: "used/pack-13/009-pumpkin.svg", platform: ["linux"], synonyms: ["text editor", "vim"], categories: ["editor"], legacyViews: 0 },
  { repo: "visual-basic-6", title: "Visual Basic 6", icon: "used/pack-3/024-magic-wand.svg", platform: ["windows"], synonyms: ["vb6", "basic"], categories: ["ide"], legacyViews: 1336 },
  { repo: "visual-spigot", title: "Visual Spigot", icon: "used/pack-10/018-owl.svg", platform: ["windows"], synonyms: ["minecraft", "plugin"], categories: ["ide"], legacyViews: 645 },
  { repo: "visual-studio-code", title: "Visual Studio Code", icon: "used/pack-1/048-frankenstein.svg", synonyms: ["vscode", "vs code", "code"], categories: ["editor"], legacyViews: 314788 },
  { repo: "visual-studio", title: "Visual Studio", icon: "used/pack-1/041-skeleton.svg", platform: ["macos", "windows"], synonyms: ["vs", "microsoft", ".net"], categories: ["ide"], legacyViews: 192815 },
  { repo: "vital", title: "Vital", icon: "used/pack-4/049-lyre.svg", synonyms: ["synth", "synthesizer", "music"], categories: ["other"], legacyViews: 170 },
  { repo: "vivado", title: "Vivado", icon: "used/pack-8/002-satellite.svg", platform: ["linux", "windows"], synonyms: ["xilinx", "fpga"], categories: ["ide"], legacyViews: 5392 },
  { repo: "vivaldi", title: "Vivaldi", icon: "used/pack-1/003-broom.svg", synonyms: ["web browser", "chromium"], categories: ["browser"], legacyViews: 18989 },
  { repo: "vortex-mod-manager", title: "Vortex Mod Manager", icon: "used/pack-2/011-game-controller.svg", platform: ["windows"], synonyms: ["mod manager", "nexus mods"], categories: ["other"], legacyViews: 265 },
  { repo: "wallpaper", title: "Wallpaper", icon: "used/pack-5/034-skull.svg", synonyms: ["desktop wallpaper", "background"], categories: ["other"], legacyViews: 102971 },
  { repo: "warp", title: "Warp", icon: "used/pack-10/003-haunted-house.svg", platform: ["macos"], synonyms: ["terminal"], categories: ["terminal"], legacyViews: 1347 },
  { repo: "waybar", title: "Waybar", icon: "used/pack-5/031-magic cape.svg", platform: ["linux"], synonyms: ["status bar", "wayland"], categories: ["other"], legacyViews: 0 },
  { repo: "wezterm", title: "WezTerm", icon: "used/pack-5/040-ticket.svg", synonyms: ["terminal emulator"], categories: ["terminal"], legacyViews: 751 },
  { repo: "windows-terminal", title: "Windows Terminal", icon: "used/pack-3/047-tube.svg", platform: ["windows"], synonyms: ["terminal"], categories: ["terminal"], legacyViews: 125652 },
  { repo: "windterm", title: "WindTerm", icon: "used/pack-9/015-finger.svg", synonyms: ["terminal", "ssh"], categories: ["terminal"], legacyViews: 803 },
  { repo: "wing", title: "Wing", icon: "used/pack-3/043-snake.svg", synonyms: ["python", "ide"], categories: ["ide"], legacyViews: 1576 },
  { repo: "WOB", title: "WOB", icon: "used/pack-1/020-halloween.svg", platform: ["linux"], synonyms: ["wayland", "overlay"], categories: ["other"], legacyViews: 0 },
  { repo: "wofi", title: "wofi", icon: "used/pack-7/050-poison.svg", platform: ["linux"], synonyms: ["launcher", "wayland", "rofi"], categories: ["other"], legacyViews: 2729 },
  { repo: "wolfram-notebooks", title: "Wolfram Notebooks", icon: "used/pack-3/002-spellbook.svg", synonyms: ["mathematica", "wolfram"], categories: ["ide"], legacyViews: 2424 },
  { repo: "wordpress", title: "Wordpress", icon: "used/pack-5/004-tarot.svg", synonyms: ["cms", "blogging", "wp"], categories: ["service"], legacyViews: 5030 },
  { repo: "wox", title: "Wox", icon: "used/pack-5/003-crystal ball.svg", platform: ["windows"], synonyms: ["launcher"], categories: ["other"], legacyViews: 11790 },
  { repo: "wp", title: "WP", icon: "used/pack-4/028-column.svg", synonyms: ["wordpress", "cli"], categories: ["terminal"], legacyViews: 87 },
  { repo: "x64dbg", title: "x64dbg", icon: "used/pack-3/017-fortune-telling.svg", platform: ["windows"], synonyms: ["debugger", "reverse engineering"], categories: ["other"], legacyViews: 0 },
  { repo: "xchat", title: "XChat", icon: "used/pack-6/001-coffin.svg", platform: ["linux", "windows"], synonyms: ["irc", "chat"], categories: ["social"], legacyViews: 5723 },
  { repo: "xcode", title: "Xcode", icon: "used/pack-3/048-unicorn.svg", platform: ["macos"], synonyms: ["swift", "ios", "apple"], categories: ["ide"], legacyViews: 102804 },
  { repo: "xdbg", title: "xdbg", icon: "used/pack-4/037-shield.svg", synonyms: ["debugger", "reverse engineering"], categories: ["other"], legacyViews: 0 },
  { repo: "xfce4-terminal", title: "Xfce4 Terminal", icon: "used/pack-7/029-clown.svg", platform: ["linux"], synonyms: ["xfce", "terminal"], categories: ["terminal"], legacyViews: 12022 },
  { repo: "xournalpp", title: "Xournal++", icon: "used/pack-7/013-witch.svg", synonyms: ["note taking", "pdf", "annotation"], categories: ["other"], legacyViews: 3379 },
  { repo: "xresources", title: "Xresources", icon: "used/pack-5/047-mortar.svg", platform: ["linux"], synonyms: ["x11", "colors"], categories: ["other"], legacyViews: 24253 },
  { repo: "yakuake", title: "Yakuake", icon: "used/pack-9/039-gift.svg", platform: ["linux"], synonyms: ["terminal", "dropdown", "kde"], categories: ["terminal"], legacyViews: 0 },
  { repo: "yazi", title: "Yazi", icon: "used/pack-3/012-dagger.svg", synonyms: ["file manager"], categories: ["terminal"], legacyViews: 0 },
  { repo: "youtube-music-desktop", title: "YouTube Music Desktop", icon: "used/pack-6/044-violin.svg", synonyms: ["youtube", "music"], categories: ["other"], legacyViews: 496 },
  { repo: "youtube", title: "Youtube", icon: "used/pack-9/005-dracula.svg", synonyms: ["video", "streaming"], categories: ["service"], legacyViews: 3375 },
  { repo: "yunohost", title: "YunoHost", icon: "used/pack-5/014-scroll.svg", synonyms: ["self-hosting", "server"], categories: ["other"], legacyViews: 183 },
  { repo: "zathura", title: "Zathura", icon: "used/pack-6/035-grave.svg", synonyms: ["pdf", "viewer"], categories: ["other"], legacyViews: 3418 },
  { repo: "zed", title: "Zed", icon: "used/pack-12/029-kappa.svg", synonyms: ["text editor", "code editor"], categories: ["editor"], legacyViews: 0 },
  { repo: "zellij", title: "Zellij", icon: "used/pack-3/004-broom.svg", platform: ["linux", "macos"], synonyms: ["terminal multiplexer", "tmux"], categories: ["terminal"], legacyViews: 516 },
  { repo: "zsh-syntax-highlighting", title: "zsh-syntax-highlighting", icon: "used/pack-10/020-reaper.svg", synonyms: ["zsh", "plugin"], categories: ["terminal"], legacyViews: 10231 },
  { repo: "zsh", title: "Zsh", icon: "used/pack-1/034-eye.svg", synonyms: ["shell", "z shell"], categories: ["terminal"], legacyViews: 276962 }
];

// { repo: "fb-messenger", title: "Facebook Messenger", icon: "used/pack-3/041-scroll.svg", synonyms: ["facebook", "messenger"], categories: ["social"], legacyViews: 12280 },
// { repo: "b4x", title: "B4X", icon: "used/pack-7/038-broom.svg", categories: ["editor", "ide"], legacyViews: 1151 },
