const paths: Paths = [
  { params: { theme: "abap", title: "ABAP", repo: "abap", color: "cyan", icon: "used/pack-10/046-rum.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 3868 } },
  { params: { theme: "ableton-live", title: "Ableton Live", repo: "ableton-live", color: "orange", icon: "used/pack-5/039-flask.svg", platform: ["osx", "windows"], categories: ["all", "others"], legacyViews: 4871 } },
  { params: { theme: "abricotine", title: "Abricotine", repo: "abricotine", color: "purple", icon: "used/pack-9/013-poison.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 983 } },
  { params: { theme: "acs", title: "ACS", repo: "acs", color: "cyan", icon: "used/pack-3/032-pendant.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 0 } },
  { params: { theme: "adminer", title: "Adminer", repo: "adminer", color: "orange", icon: "used/pack-8/005-moon.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 3123 } },
  { params: { theme: "adobe", title: "Adobe", repo: "adobe", color: "pink", icon: "used/pack-6/039-zombie.svg", platform: ["osx", "windows"], synonyms: ["photoshop", "illustrator"], categories: ["all", "others", "services"], legacyViews: 11244 } },
  { params: { theme: "adventofcode", title: "Advent of Code", repo: "adventofcode", color: "cyan", icon: "used/pack-2/009-tetris.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "aerc", title: "aerc", repo: "aerc", color: "cyan", icon: "used/pack-4/010-centaur.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "alacritty", title: "Alacritty", repo: "alacritty", color: "pink", icon: "used/pack-6/004-reaper.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 30582 } },
  { params: { theme: "albert", title: "Albert", repo: "albert", color: "pink", icon: "used/pack-7/011-food.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 1470 } },
  { params: { theme: "alfred", title: "Alfred", repo: "alfred", color: "purple", icon: "used/pack-5/019-wizard hat.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 18846 } },
  { params: { theme: "aliucord", title: "Aliucord", repo: "aliucord", color: "purple", icon: "used/pack-9/027-candy-cane.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 2845 } },
  { params: { theme: "amfora", title: "Amfora", repo: "amfora", color: "cyan", icon: "used/pack-9/011-bucket.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 470 } },
  { params: { theme: "anne-pro-2", title: "Anne Pro 2", color: "cyan", repo: "anne-pro-2", icon: "used/pack-9/043-halloween.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "apollo", title: "Apollo", repo: "apollo", color: "purple", icon: "used/pack-8/001-space.svg", platform: ["osx"], synonyms: ["reddit"], categories: ["all", "others"], legacyViews: 1076 } },
  { params: { theme: "archive-of-our-own", title: "Archive of Our Own", repo: "archive-of-our-own", color: "cyan", icon: "used/pack-3/008-chest.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 438 } },
  { params: { theme: "arduino-ide", title: "Arduino IDE", repo: "arduino-ide", color: "cyan", icon: "used/pack-1/001-gallows.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 12946 } },
  { params: { theme: "arduino-pro-ide", title: "Arduino Pro IDE", repo: "arduino-pro-ide", color: "purple", icon: "used/pack-7/014-cauldron.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 2250 } },
  { params: { theme: "aseprite", title: "Aseprite", repo: "aseprite", color: "orange", icon: "used/pack-8/006-asteroid.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 6361 } },
  { params: { theme: "atom", title: "Atom", repo: "atom", color: "purple", icon: "used/pack-1/005-potion.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 81218 } },
  { params: { theme: "audacity", title: "Audacity", repo: "audacity", color: "cyan", icon: "used/pack-3/020-magic-ball.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "auto-ao3-app", title: "AutoAO3App", repo: "auto-ao3-app", color: "yellow", icon: "used/pack-5/028-magic hat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 102 } },
  { params: { theme: "b4x", title: "B4X", repo: "b4x", color: "purple", icon: "used/pack-7/038-broom.svg", platform: ["all"], categories: ["all", "editors", "ides"], legacyViews: 1151 } },
  { params: { theme: "bandcamp", title: "Bandcamp", repo: "bandcamp", color: "purple", icon: "used/pack-4/002-grapes.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "base16", title: "Base16", repo: "base16-dracula-scheme", color: "purple", icon: "used/pack-6/030-graveyard.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 9431 } },
  { params: { theme: "bashtop", title: "Bashtop", repo: "bashtop", color: "purple", icon: "used/pack-7/044-monster.svg", platform: ["linux", "osx"], categories: ["all", "others"], legacyViews: 3631 } },
  { params: { theme: "bbedit", title: "BBEdit", repo: "bbedit", color: "cyan", icon: "used/pack-4/041-cyclops.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 6306 } },
  { params: { theme: "beamer", title: "Beamer", repo: "beamer", color: "purple", icon: "used/pack-10/048-zombie.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1513 } },
  { params: { theme: "bear", title: "Bear", repo: "bear", color: "orange", icon: "used/pack-1/008-tree.svg", platform: ["osx"], categories: ["all", "editors", "services"], legacyViews: 3446 } },
  { params: { theme: "bemenu", title: "bemenu", repo: "bemenu", color: "purple", icon: "used/pack-7/027-gifts.svg", platform: ["linux", "osx"], categories: ["all", "others"], legacyViews: 1056 } },
  { params: { theme: "betterdiscord", title: "BetterDiscord", repo: "betterdiscord", color: "pink", icon: "used/pack-2/030-game-controller.svg", platform: ["all"], categories: ["all", "others", "social", "services"], legacyViews: 37345 } },
  { params: { theme: "beyond-compare-4", title: "Beyond Compare 4", repo: "beyond-compare-4", color: "orange", icon: "used/pack-10/050-scarecrow.svg", platform: ["all"], categories: ["all", "editors", "services"], legacyViews: 2092 } },
  { params: { theme: "blender", title: "Blender", repo: "blender", color: "pink", icon: "used/pack-2/029-bomb.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 10649 } },
  { params: { theme: "blink-shell", title: "Blink Shell", repo: "blink-shell", color: "pink", icon: "used/pack-2/038-3d glasses.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 263 } },
  { params: { theme: "blockbench", title: "Blockbench", repo: "blockbench", color: "pink", icon: "used/pack-2/034-video card.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "bobthefish", title: "bobthefish", repo: "bobthefish", color: "purple", icon: "used/pack-10/001-witch.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 529 } },
  { params: { theme: "bookwyrm", title: "BookWyrm", repo: "bookwyrm", color: "purple", icon: "used/pack-4/012-laurel.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "brackets", title: "Brackets", repo: "brackets", color: "orange", icon: "used/pack-4/043-minotaur.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 27630 } },
  { params: { theme: "bspwm", title: "bspwm", repo: "bspwm", color: "purple", icon: "used/pack-6/022-candle.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 8603 } },
  { params: { theme: "btcpay-server", title: "BTCPay Server", repo: "btcpay-server", color: "purple", icon: "used/pack-9/048-bat.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 398 } },
  { params: { theme: "campfire", title: "Campfire", repo: "campfire", color: "orange", icon: "used/pack-7/020-lantern.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 137 } },
  { params: { theme: "caprine-messenger", title: "Caprine Messenger", repo: "caprine-messenger", color: "purple", icon: "used/pack-10/033-crow.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 608 } },
  { params: { theme: "cava", title: "Cava", repo: "cava", color: "cyan", icon: "used/pack-3/038-rainbow.svg", platform: ["linux", "osx"], categories: ["all", "others"], legacyViews: 173 } },
  { params: { theme: "chatterino", title: "Chatterino", color: "purple", repo: "chatterino", icon: "used/pack-3/031-mushroom.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "chrome", title: "Chrome", repo: "google-chrome", color: "orange", icon: "used/pack-10/007-pumpkins.svg", platform: ["all"], synonyms: ["google"], categories: ["all", "browsers"], legacyViews: 96243 } },
  { params: { theme: "cider", title: "Cider", repo: "cider", color: "pink", icon: "used/pack-1/009-costume.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 732 } },
  { params: { theme: "cli-visualizer", title: "Cli-Visualizer", repo: "cli-visualizer", color: "purple", icon: "used/pack-2/006-puzzle.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "clone-hero", title: "Clone Hero", repo: "clone-hero", color: "purple", icon: "used/pack-2/036-game-controller.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 840 } },
  { params: { theme: "cmder", title: "Cmder", repo: "cmder", color: "orange", icon: "used/pack-1/006-night.svg", platform: ["windows"], categories: ["all", "terminals"], legacyViews: 17970 } },
  { params: { theme: "coda", title: "Coda", repo: "coda", color: "pink", icon: "used/pack-1/013-lollipop.svg", platform: ["osx"], categories: ["all", "editors"], legacyViews: 8975 } },
  { params: { theme: "codeblocks", title: "Code::Blocks", repo: "codeblocks", color: "cyan", icon: "used/pack-5/010-toolbox.svg", platform: ["all"], categories: ["all", "editors", "ides"], legacyViews: 20722 } },
  { params: { theme: "codepen", title: "CodePen", repo: "codepen", color: "cyan", icon: "used/pack-9/049-magic-wand.svg", platform: ["all"], categories: ["all", "editors", "services"], legacyViews: 476 } },
  { params: { theme: "coderunner", title: "CodeRunner", repo: "coderunner", color: "orange", icon: "used/pack-10/024-cupcake.svg", platform: ["osx"], categories: ["all", "editors"], legacyViews: 494 } },
  { params: { theme: "color-slurp", title: "ColorSlurp", repo: "color-slurp", color: "purple", icon: "used/pack-2/013-darts.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 154 } },
  { params: { theme: "colorls", title: "colorls", repo: "colorls", color: "cyan", icon: "used/pack-2/026-building.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 6673 } },
  { params: { theme: "conemu", title: "ConEmu", repo: "conemu", color: "pink", icon: "used/pack-1/010-trident.svg", platform: ["windows"], categories: ["all", "terminals"], legacyViews: 32516 } },
  { params: { theme: "copyq", title: "CopyQ", repo: "copyq", color: "cyan", icon: "used/pack-8/009-robot.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1497 } },
  { params: { theme: "coteditor", title: "CotEditor", repo: "coteditor", color: "cyan", icon: "used/pack-1/026-mummy.svg", platform: ["osx"], categories: ["all", "editors"], legacyViews: 1719 } },
  { params: { theme: "couscous", title: "Couscous", repo: "couscous", color: "cyan", icon: "used/pack-1/024-tombstone-1.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2001 } },
  { params: { theme: "cryptowatch", title: "Cryptowatch", repo: "cryptowatch", color: "purple", icon: "used/pack-7/037-halloween.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1589 } },
  { params: { theme: "delphi", title: "Delphi", repo: "delphi", color: "yellow", icon: "used/pack-9/032-tree.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 875 } },
  { params: { theme: "dev-cpp", title: "Dev-C++", repo: "dev-cpp", color: "cyan", icon: "used/pack-9/021-scream.svg", platform: ["windows"], categories: ["all", "ides"], legacyViews: 9935 } },
  { params: { theme: "dircolors", title: ".dircolors", repo: "dircolors", color: "purple", icon: "used/pack-9/037-paper-bag.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 895 } },
  { params: { theme: "discordbotmaker", title: "Discord Bot Maker", repo: "discordbotmaker", color: "pink", icon: "used/pack-10/041-potion.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 2299 } },
  { params: { theme: "discourse", title: "Discourse", repo: "discourse", color: "orange", icon: "used/pack-7/032-bat.svg", platform: ["all"], categories: ["all", "others", "social"], legacyViews: 3377 } },
  { params: { theme: "ditto", title: "Ditto", repo: "ditto", color: "pink", icon: "used/pack-7/023-balloons.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 1117 } },
  { params: { theme: "dmenu", title: "Dmenu", repo: "dmenu", color: "orange", icon: "used/pack-1/012-bag.svg", platform: ["linux"], categories: ["all", "others", "terminals"], legacyViews: 352 } },
  { params: { theme: "doom-emacs", title: "DOOM Emacs", repo: "doom-emacs", color: "cyan", icon: "used/pack-7/007-living-dead.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 6209 } },
  { params: { theme: "drafts", title: "Drafts", repo: "drafts", color: "yellow", icon: "used/pack-5/006-treasure-chest.svg", platform: ["osx"], categories: ["all", "editors"], legacyViews: 345 } },
  { params: { theme: "duckduckgo", title: "DuckDuckGo", repo: "duckduckgo", color: "orange", icon: "used/pack-1/002-coffin.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 12132 } },
  { params: { theme: "dunst", title: "Dunst", repo: "dunst", color: "yellow", icon: "used/pack-7/033-trident.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3327 } },
  { params: { theme: "duolingo", title: "Duolingo", repo: "duolingo", color: "green", icon: "used/pack-12/015-athena.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 0 } },
  { params: { theme: "dwarf-fortress", title: "Dwarf Fortress", repo: "dwarf-fortress", color: "purple", icon: "used/pack-10/038-dwarf.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1011 } },
  { params: { theme: "dyalog", title: "Dyalog APL", repo: "dyalog", color: "purple", icon: "used/pack-4/027-flag.svg", platform: ["windows"], categories: ["all", "editors"], legacyViews: 77 } },
  { params: { theme: "eclipse", title: "Eclipse", repo: "eclipse", color: "orange", icon: "used/pack-7/008-full moon.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 61636 } },
  { params: { theme: "editplus", title: "Editplus", repo: "editplus", color: "purple", icon: "used/pack-1/023-bones.svg", platform: ["windows"], categories: ["all", "editors", "ides"], legacyViews: 2688 } },
  { params: { theme: "em-client", title: "eM Client", repo: "em-client", color: "purple", icon: "used/pack-9/009-broomstick.svg", platform: ["osx", "windows"], categories: ["all", "others"], legacyViews: 885 } },
  { params: { theme: "emacs", title: "Emacs", repo: "emacs", color: "pink", icon: "used/pack-1/018-devil.svg", platform: ["all"], categories: ["all", "editors", "terminals"], legacyViews: 82188 } },
  { params: { theme: "everythingtoolbar", title: "EverythingToolbar", repo: "everythingtoolbar", color: "purple", icon: "used/pack-7/019-mask.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 1796 } },
  { params: { theme: "exa", title: "exa", repo: "exa", color: "cyan", icon: "used/pack-10/014-vampire.svg", platform: ["linux, osx"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "facebook-messenger", title: "Facebook Messenger", repo: "fb-messenger", color: "purple", icon: "used/pack-3/041-scroll.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 12280 } },
  { params: { theme: "fedilab", title: "Fedilab", repo: "fedilab", color: "cyan", icon: "used/pack-8/013-capsule.svg", platform: ["all"], categories: ["all", "others", "social"], legacyViews: 7 } },
  { params: { theme: "fig", title: "Fig", repo: "fig", color: "purple", icon: "used/pack-9/026-castle.svg", platform: ["osx"], categories: ["all", "terminals", "services"], legacyViews: 795 } },
  { params: { theme: "figma", title: "Figma", repo: "figma", color: "cyan", icon: "used/pack-4/044-werewolf.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 10188 } },
  { params: { theme: "files", title: "Files", repo: "files", color: "cyan", icon: "used/pack-10/016-pumpkin.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 7582 } },
  { params: { theme: "firefox", title: "Firefox", repo: "firefox", color: "purple", icon: "used/pack-1/028-finger.svg", platform: ["all"], categories: ["all", "browsers"], legacyViews: 42358 } },
  { params: { theme: "fish", title: "Fish", repo: "fish", color: "orange", icon: "used/pack-1/011-poison.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 12681 } },
  { params: { theme: "fl-studio-21", title: "FL Studio 21", repo: "fl-studio-21", color: "orange", icon: "used/pack-4/022-harp.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 709 } },
  { params: { theme: "flarum", title: "Flarum", repo: "flarum", color: "orange", icon: "used/pack-10/030-lantern.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 888 } },
  { params: { theme: "florisboard", title: "FlorisBoard", repo: "florisboard", color: "purple", icon: "used/pack-9/024-candle.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1304 } },
  { params: { theme: "flowlab", title: "Flowlab", repo: "flowlab", color: "yellow", icon: "used/pack-2/007-mobile-game.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 485 } },
  { params: { theme: "fluent-terminal", title: "Fluent Terminal", repo: "fluent-terminal", color: "orange", icon: "used/pack-1/049-bats.svg", platform: ["windows"], categories: ["all", "terminals"], legacyViews: 9809 } },
  { params: { theme: "fman", title: "fman", repo: "fman", color: "cyan", icon: "used/pack-8/028-alien.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1145 } },
  { params: { theme: "fontforge", title: "FontForge", color: "purple", repo: "fontforge", icon: "used/pack-4/019-parthenon.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "foot-terminal", title: "foot", repo: "foot", color: "orange", icon: "used/pack-6/042-corpse.svg", platform: ["linux"], categories: ["all", "terminals"], legacyViews: 860 } },
  { params: { theme: "forklift", title: "ForkLift", repo: "forklift", color: "yellow", icon: "used/pack-13/023-cemetery.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "freecad", title: "FreeCAD", repo: "freecad", color: "yellow", icon: "used/pack-2/018-jenga.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1917 } },
  { params: { theme: "freetube", title: "FreeTube", repo: "freetube", color: "yellow", icon: "used/pack-8/023-monkey.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 0 } },
  { params: { theme: "funkwhale", title: "Funkwhale", repo: "funkwhale", color: "purple", icon: "used/pack-9/044-scythe.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 455 } },
  { params: { theme: "fuzzel", title: "fuzzel", repo: "fuzzel", color: "cyan", icon: "used/pack-11/046-robot.svg", platform: ["linux"], categories: ["all", "others", "terminals"], legacyViews: 0 } },
  { params: { theme: "fzf", title: "FZF", repo: "fzf", color: "purple", icon: "used/pack-10/027-eyeball.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1745 } },
  { params: { theme: "gajim", title: "Gajim", repo: "gajim", color: "cyan", icon: "used/pack-10/005-bat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 386 } },
  { params: { theme: "gamemaker-studio", title: "GameMaker Studio", repo: "gamemaker-studio", color: "cyan", icon: "used/pack-1/031-serial-killer.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 8991 } },
  { params: { theme: "gamepad-viewer", title: "Gamepad Viewer", repo: "gamepad-viewer", color: "pink", icon: "used/pack-2/010-game-controller.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1633 } },
  { params: { theme: "geany", title: "Geany", repo: "geany", color: "orange", icon: "used/pack-3/009-crystal-ball.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 5988 } },
  { params: { theme: "gedit", title: "Gedit", repo: "gedit", color: "cyan", icon: "used/pack-1/036-spellbook.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 34791 } },
  { params: { theme: "gh-dash", title: "GH-Dash", color: "purple", repo: "gh-dash", icon: "used/pack-3/046-trick.svg", platform: ["all"], categories: ["all", "terminal"], legacyViews: 0 } },
  { params: { theme: "ghostwriter", title: "ghostwriter", repo: "ghostwriter", color: "cyan", icon: "used/pack-10/012-ghost.svg", platform: ["windows", "linux"], categories: ["all", "others"], legacyViews: 1154 } },
  { params: { theme: "gimp", title: "GIMP", repo: "gimp", color: "yellow", icon: "used/pack-5/001-magic-wand.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 860 } },
  { params: { theme: "git", title: "Git", repo: "git", color: "cyan", icon: "used/pack-3/003-book.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 3847 } },
  { params: { theme: "github-pages", title: "GitHub Pages", repo: "gh-pages", color: "cyan", icon: "used/pack-1/037-candies.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 17104 } },
  { params: { theme: "github", title: "GitHub", repo: "github", color: "purple", icon: "used/pack-7/045-cat.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 7033 } },
  { params: { theme: "gitk", title: "Gitk", repo: "gitk", color: "purple", icon: "used/pack-5/020-saw.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 10713 } },
  { params: { theme: "gitkraken", title: "GitKraken", repo: "gitkraken", color: "cyan", icon: "used/pack-9/033-bug.svg", platform: ["all"], categories: ["all", "services", "terminals"], legacyViews: 1308 } },
  { params: { theme: "gitlab", title: "GitLab", repo: "gitlab", color: "orange", icon: "used/pack-10/009-cat.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 1776 } },
  { params: { theme: "gmk", title: "GMK", repo: "gmk", color: "orange", icon: "used/pack-4/016-axe.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 19006 } },
  { params: { theme: "gnome-terminal", title: "Gnome Terminal", repo: "gnome-terminal", color: "orange", icon: "used/pack-6/040-crow.svg", platform: ["linux"], categories: ["all", "terminals"], legacyViews: 179027 } },
  { params: { theme: "godot", title: "Godot", repo: "godot", color: "pink", icon: "used/pack-7/024-skeleton.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 8189 } },
  { params: { theme: "google-calendar", title: "Google Calendar", color: "orange", repo: "google-calendar", icon: "used/pack-10/015-halloween.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "grub", title: "GRUB", repo: "grub", color: "yellow", icon: "used/pack-9/045-spider.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 7947 } },
  { params: { theme: "gtk", title: "GTK", repo: "gtk", color: "purple", icon: "used/pack-5/008-wizard.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 111125 } },
  { params: { theme: "hacker-news", title: "Hacker News", repo: "hacker-news", color: "cyan", icon: "used/pack-8/021-satellite.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 477 } },
  { params: { theme: "harpy-for-twitter", title: "Harpy for Twitter", repo: "harpy-for-twitter", color: "purple", icon: "used/pack-4/008-griffin.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 4 } },
  { params: { theme: "heroic-games-launcher", title: "Heroic Games Launcher", repo: "heroic-games-launcher", color: "pink", icon: "used/pack-2/017-arcade.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "highlightjs", title: "Highlight.js", repo: "highlightjs", color: "orange", icon: "used/pack-6/032-graveyard.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 19432 } },
  { params: { theme: "homepage-app", title: "Homepage", repo: "homepage-app", color: "cyan", icon: "used/pack-3/011-magician-hat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "homer", title: "Homer", repo: "homer", color: "purple", icon: "used/pack-10/029-candies.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1503 } },
  { params: { theme: "hyper", title: "Hyper", repo: "hyper", color: "orange", icon: "used/pack-1/025-candle-1.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 81376 } },
  { params: { theme: "hyprland", title: "Hyprland", repo: "hyprland", color: "pink", icon: "used/pack-13/015-eye ball.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "i3", title: "i3", repo: "i3", color: "orange", icon: "used/pack-1/016-candies-1.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 22389 } },
  { params: { theme: "i3lock-color", title: "i3lock-color", repo: "i3lock-color", color: "cyan", icon: "used/pack-5/022-padlock.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 218 } },
  { params: { theme: "ida", title: "IDA Pro", repo: "ida", color: "cyan", icon: "used/pack-7/018-cleaver.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4300 } },
  { params: { theme: "idle", title: "IDLE", repo: "idle", color: "cyan", icon: "used/pack-5/042-handcuffs.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 8443 } },
  { params: { theme: "imageglass", title: "ImageGlass", repo: "imageglass", color: "purple", icon: "used/pack-10/032-crystal.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 650 } },
  { params: { theme: "infinity-for-reddit", title: "Infinity for Reddit", repo: "infinity-for-reddit", color: "cyan", icon: "used/pack-8/016-galaxy.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 7 } },
  { params: { theme: "inkscape", title: "Inkscape", repo: "inkscape", color: "purple", icon: "used/pack-7/030-skull.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2818 } },
  { params: { theme: "insomnia", title: "Insomnia", repo: "insomnia", color: "cyan", icon: "used/pack-1/043-scythe.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 25560 } },
  { params: { theme: "ish", title: "iSH", repo: "ish", color: "pink", icon: "used/pack-6/031-broken.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 0 } },
  { params: { theme: "iterm", title: "iTerm", repo: "iterm", color: "pink", icon: "used/pack-7/042-haunted house.svg", platform: ["osx"], categories: ["all", "terminals"], legacyViews: 359069 } },
  { params: { theme: "itfy", title: "ITFY", repo: "itfy", color: "orange", icon: "used/pack-10/040-skeleton.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 273 } },
  { params: { theme: "jabref", title: "Jabref", repo: "jabref", color: "pink", icon: "used/pack-1/022-witch.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "javadoc", title: "Javadoc", repo: "javadoc", color: "cyan", icon: "used/pack-2/043-sword.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2947 } },
  { params: { theme: "jdownloader2", title: "JDownloader2", repo: "jdownloader2", color: "cyan", icon: "used/pack-3/001-fairy-dust.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1324 } },
  { params: { theme: "jetbrains", title: "JetBrains", repo: "jetbrains", color: "pink", icon: "used/pack-1/046-zombie.svg", platform: ["all"], synonyms: ["intellij", "pycharm", "webstorm", "phpstorm", "rider", "clion", "datagrip", "rubymine", "appcode", "goland"], categories: ["all", "services", "editors", "ides"], legacyViews: 156545 } },
  { params: { theme: "jgrasp", title: "jGrasp", repo: "jgrasp", color: "orange", icon: "used/pack-1/007-guillotine.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 5084 } },
  { params: { theme: "joplin", title: "Joplin", repo: "joplin", color: "orange", icon: "used/pack-10/006-coffin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 786 } },
  { params: { theme: "jupyter-notebook", title: "Jupyter Notebook", repo: "jupyter-notebook", color: "pink", icon: "used/pack-11/037-alien.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 0 } },
  { params: { theme: "jupyterlab", title: "JupyterLab", repo: "jupyterlab", color: "purple", icon: "used/pack-6/012-candles.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 13539 } },
  { params: { theme: "kakoune", title: "Kakoune", repo: "kakoune", color: "orange", icon: "used/pack-1/033-black-cat.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 1870 } },
  { params: { theme: "kanbanflow", title: "KanbanFlow", repo: "kanbanflow", color: "purple", icon: "used/pack-9/038-candy-corn.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 141 } },
  { params: { theme: "kate", title: "Kate", repo: "kate", color: "orange", icon: "used/pack-5/033-smoke.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 15371 } },
  { params: { theme: "kdiff3", title: "KDiff3", repo: "kdiff3", color: "orange", icon: "used/pack-10/047-gate.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1507 } },
  { params: { theme: "keypirinha", title: "Keypirinha", repo: "keypirinha", color: "orange", icon: "used/pack-1/004-fear.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 1143 } },
  { params: { theme: "kicad", title: "KiCad", repo: "kicad", color: "orange", icon: "used/pack-7/015-witch-hat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3376 } },
  { params: { theme: "kitty", title: "Kitty", repo: "kitty", color: "orange", icon: "used/pack-1/015-makeup.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 14047 } },
  { params: { theme: "konsole", title: "Konsole", repo: "konsole", color: "orange", icon: "used/pack-3/035-potion-1.svg", platform: ["linux"], categories: ["all", "terminals"], legacyViews: 40856 } },
  { params: { theme: "kristall", title: "Kristall", repo: "kristall", color: "pink", icon: "used/pack-5/018-magic wand.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "krita", title: "Krita", repo: "krita", color: "orange", icon: "used/pack-10/028-poison.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1179 } },
  { params: { theme: "kurozora", title: "Kurozora", repo: "kurozora", color: "cyan", icon: "used/pack-13/003-pumpkin.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 0 } },
  { params: { theme: "labplot", title: "LabPlot", color: "cyan", repo: "labplot", icon: "used/pack-8/033-planet.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "latex", title: "LaTeX", repo: "latex", color: "cyan", icon: "used/pack-9/023-pumpkin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3401 } },
  { params: { theme: "lcd-smartie", title: "LCD Smartie", color: "yellow", repo: "lcd-smartie", icon: "used/pack-9/031-blood-transfusion.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "leftwm", title: "leftwm", repo: "leftwm", color: "orange", icon: "used/pack-5/021-magic trick.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 163 } },
  { params: { theme: "libreddit", title: "Libreddit", repo: "libreddit", color: "yellow", icon: "used/pack-4/025-amphora.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "libreoffice", title: "LibreOffice", repo: "libreoffice", color: "purple", icon: "used/pack-7/010-spellbook.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 9430 } },
  { params: { theme: "lichess", title: "Lichess", repo: "lichess", color: "yellow", icon: "used/pack-2/032-chess.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "light-table", title: "Light Table", repo: "light-table", color: "orange", icon: "used/pack-1/050-pumpkin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 7871 } },
  { params: { theme: "lightpaper", title: "LightPaper", repo: "lightpaper", color: "purple", icon: "used/pack-5/030-voodoo.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 3638 } },
  { params: { theme: "limechat", title: "LimeChat", repo: "limechat", color: "purple", icon: "used/pack-3/016-fire.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 1142 } },
  { params: { theme: "linear", title: "Linear", repo: "linear", color: "pink", icon: "used/pack-8/015-planet.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 1286 } },
  { params: { theme: "liteide", title: "LiteIDE", repo: "liteide", color: "cyan", icon: "used/pack-7/041-spider.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1283 } },
  { params: { theme: "logseq", title: "Logseq", repo: "logseq", color: "pink", icon: "used/pack-8/032-constellation.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4207 } },
  { params: { theme: "lsd", title: "lsd", repo: "lsd", color: "yellow", icon: "used/pack-13/025-fairy.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "ltspice", title: "LTSpice", repo: "ltspice", color: "purple", icon: "used/pack-7/048-coffin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1004 } },
  { params: { theme: "lxterminal", title: "LXTerminal", repo: "lxterminal", color: "cyan", icon: "used/pack-10/039-balloon.svg", platform: ["linux"], categories: ["all", "terminals"], legacyViews: 1397 } },
  { params: { theme: "macdown", title: "MacDown", repo: "macdown", color: "orange", icon: "used/pack-1/042-candle.svg", platform: ["osx"], categories: ["all", "editors"], legacyViews: 7540 } },
  { params: { theme: "macos-color-picker", title: "macOS Color Picker", repo: "macos-color-picker", color: "pink", icon: "used/pack-3/010-crystal.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 1131 } },
  { params: { theme: "mailspring", title: "Mailspring", repo: "mailspring", color: "purple", icon: "used/pack-7/009-owl.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 5848 } },
  { params: { theme: "makehuman", title: "Makehuman", repo: "makehuman", color: "orange", icon: "used/pack-3/026-spell.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "mako", title: "Mako", repo: "mako", color: "cyan", icon: "used/pack-10/037-ghost-1.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 591 } },
  { params: { theme: "man-pages", title: "man-pages", repo: "man-pages", color: "orange", icon: "used/pack-10/043-prisoner.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "mantine", title: "Mantine", color: "purple", repo: "mantine", icon: "used/pack-3/014-fairy.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "marp", title: "Marp", repo: "marp", color: "pink", icon: "used/pack-7/036-party.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3314 } },
  { params: { theme: "matlab", title: "MATLAB", repo: "matlab", color: "cyan", icon: "used/pack-7/049-grim-reaper.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 5296 } },
  { params: { theme: "matplotlib", title: "Matplotlib", repo: "matplotlib", color: "purple", icon: "used/pack-7/021-frankenstein.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2171 } },
  { params: { theme: "mattermost", title: "Mattermost", repo: "mattermost", color: "pink", icon: "used/pack-1/019-spider.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4649 } },
  { params: { theme: "metaeditor", title: "MetaEditor", repo: "metaeditor", color: "orange", icon: "used/pack-10/035-gift.svg", platform: ["windows"], categories: ["all", "editors"], legacyViews: 1324 } },
  { params: { theme: "metatrader5", title: "MetaTrader 5", repo: "metatrader5", color: "cyan", icon: "used/pack-9/036-witch-hat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3090 } },
  { params: { theme: "micro", title: "Micro", repo: "micro", color: "purple", icon: "used/pack-3/019-lantern.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2415 } },
  { params: { theme: "microsoft-edge", title: "Microsoft Edge", color: "purple", repo: "microsoft-edge", icon: "used/pack-13/027-ghost.svg", platform: ["all"], categories: ["all", "browsers"], legacyViews: 0 } },
  { params: { theme: "midnight-commander", title: "Midnight Commander", repo: "midnight-commander", color: "purple", icon: "used/pack-3/030-moon.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 8139 } },
  { params: { theme: "mindnode", title: "MindNode", repo: "mindnode", color: "purple", icon: "used/pack-5/007-magic-mirror.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 5614 } },
  { params: { theme: "minecraft", title: "Minecraft", repo: "minecraft", color: "cyan", icon: "used/pack-2/045-computer game.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 604 } },
  { params: { theme: "mintty", title: "Mintty", repo: "mintty", color: "cyan", icon: "used/pack-1/014-voodoo-doll.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 22290 } },
  { params: { theme: "misskey", title: "Misskey", repo: "misskey", color: "orange", icon: "used/pack-4/009-hephaestus-1.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "mixplorer", title: "MiXplorer", repo: "mixplorer", color: "cyan", icon: "used/pack-9/029-spellbook.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 1520 } },
  { params: { theme: "mkdocs", title: "MkDocs", repo: "mkdocs", color: "yellow", icon: "used/pack-13/043-bible.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "mobaxterm", title: "MobaXterm", repo: "mobaxterm", color: "cyan", icon: "used/pack-3/042-skull.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 15362 } },
  { params: { theme: "monkeytype", title: "Monkeytype", repo: "monkeytype", color: "purple", icon: "used/pack-10/004-mummy.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 890 } },
  { params: { theme: "monodevelop", title: "MonoDevelop", repo: "monodevelop", color: "pink", icon: "used/pack-1/027-hand.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 13587 } },
  { params: { theme: "mousepad", title: "Mousepad", repo: "mousepad", color: "cyan", icon: "used/pack-2/022-mouse.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 7044 } },
  { params: { theme: "musicbee", title: "MusicBee", repo: "musicbee", color: "purple", icon: "used/pack-3/022-magic.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1757 } },
  { params: { theme: "musikcube", title: "musikcube", repo: "musikcube", color: "purple", icon: "used/pack-9/020-bomb.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 399 } },
  { params: { theme: "mutt", title: "Mutt", repo: "mutt", color: "purple", icon: "used/pack-3/045-tree.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 10013 } },
  { params: { theme: "mysql-workbench", title: "MySQL Workbench", repo: "mysql-workbench", color: "orange", icon: "used/pack-9/040-scarecrow.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 8728 } },
  { params: { theme: "ncspot", title: "ncspot", repo: "ncspot", color: "purple", icon: "used/pack-7/039-tombstone.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 837 } },
  { params: { theme: "netbeans", title: "Netbeans", repo: "netbeans", color: "orange", icon: "used/pack-7/017-scarecrow.svg", platform: ["all"], categories: ["all", "editors", "ides"], legacyViews: 126987 } },
  { params: { theme: "new-tabs", title: "New Tabs", repo: "new-tabs", color: "cyan", icon: "used/pack-5/017-magician hat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 9 } },
  { params: { theme: "newsboat", title: "Newsboat", repo: "newsboat", color: "cyan", icon: "used/pack-7/047-vampire.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "newterm2", title: "NewTerm2", repo: "NewTerm2", color: "orange", icon: "used/pack-7/026-mask.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 0 } },
  { params: { theme: "nextcloud", title: "Nextcloud", repo: "nextcloud", color: "cyan", icon: "used/pack-2/044-podium.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 566 } },
  { params: { theme: "ngenuity", title: "HyperX NGNUITY", repo: "ngenuity", color: "yellow", icon: "used/pack-3/018-key.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 605 } },
  { params: { theme: "nitter", title: "Nitter", repo: "nitter", color: "orange", icon: "used/pack-4/007-owl.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 8 } },
  { params: { theme: "nnn", title: "nnn", repo: "nnn", color: "cyan", icon: "used/pack-3/050-wand.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 0 } },
  { params: { theme: "node-console", title: "Node Console", repo: "node-console", color: "cyan", icon: "used/pack-9/025-owl.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 1150 } },
  { params: { theme: "noir", title: "Noir", repo: "noir", color: "purple", icon: "used/pack-8/036-eclipse.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 394 } },
  { params: { theme: "notepad-plus-plus", title: "Notepad++", repo: "notepad-plus-plus", color: "cyan", icon: "used/pack-7/002-ghosts.svg", platform: ["windows"], categories: ["all", "editors"], legacyViews: 862543 } },
  { params: { theme: "notesnook", title: "Notesnook", color: "yellow", repo: "notesnook", icon: "used/pack-9/004-werewolf.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "nova-launcher", title: "Nova Launcher", repo: "nova-launcher", color: "purple", icon: "used/pack-9/003-witch.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 1945 } },
  { params: { theme: "nova", title: "Nova", repo: "nova", color: "pink", icon: "used/pack-8/037-meteor.svg", platform: ["osx"], categories: ["all", "editors"], legacyViews: 1728 } },
  { params: { theme: "novel-writer", title: "novelWriter", repo: "novel-writer", color: "orange", icon: "used/pack-5/043-stage.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 137 } },
  { params: { theme: "nylas-n1", title: "Nylas N1", repo: "nylas-n1", color: "orange", icon: "used/pack-5/045-hourglass.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4077 } },
  { params: { theme: "nyxt", title: "Nyxt", repo: "nyxt", color: "cyan", icon: "used/pack-9/047-cauldron.svg", platform: ["linux", "osx"], categories: ["all", "others"], legacyViews: 727 } },
  { params: { theme: "obsidian", title: "Obsidian", repo: "obsidian", color: "pink", icon: "used/pack-5/036-gemstone.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 11084 } },
  { params: { theme: "oh-my-posh", title: "Oh My Posh", repo: "oh-my-posh", color: "pink", icon: "used/pack-7/046-zombie.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 4106 } },
  { params: { theme: "omglol", title: "omg.lol", repo: "omglol", color: "orange", icon: "used/pack-4/001-zeus.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 199 } },
  { params: { theme: "onecommander", title: "OneCommander", color: "purple", repo: "onecommander", icon: "used/pack-10/008-cemetery.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "openbox", title: "Openbox", repo: "openbox", color: "pink", icon: "used/pack-2/041-box.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 1205 } },
  { params: { theme: "oracle-sql-developer", title: "Oracle SQL Developer", repo: "oracle-sql-developer", color: "purple", icon: "used/pack-1/029-werewolf.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 73678 } },
  { params: { theme: "pandoc", title: "Pandoc", repo: "pandoc", color: "purple", icon: "used/pack-9/035-black-cat.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1387 } },
  { params: { theme: "pantheon-terminal", title: "Pantheon Terminal", repo: "pantheon-terminal", color: "purple", icon: "used/pack-9/041-torch.svg", platform: ["linux"], categories: ["all", "terminals"], legacyViews: 824 } },
  { params: { theme: "papirus-folders", title: "Papirus Folders", repo: "papirus-folders", color: "orange", icon: "used/pack-3/005-candle.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "passky", title: "Passky", repo: "passky", color: "cyan", icon: "used/pack-9/012-skull.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 452 } },
  { params: { theme: "peacock-extension", title: "Peacock Extension", repo: "peacock-extension", color: "cyan", icon: "used/pack-4/005-dove.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 109 } },
  { params: { theme: "plank", title: "Plank", repo: "plank", color: "cyan", icon: "used/pack-4/029-trireme.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3329 } },
  { params: { theme: "plsql-developer", title: "PL/SQL Developer", repo: "plsql-developer", color: "orange", icon: "used/pack-10/026-pirate.svg", platform: ["all"], categories: ["all", "ides"], legacyViews: 167 } },
  { params: { theme: "plymouth", title: "Plymouth", repo: "plymouth", color: "cyan", icon: "used/pack-13/039-dessert.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "polybar", title: "Polybar", color: "cyan", repo: "polybar", icon: "used/pack-12/017-aphrodite.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "polymc", title: "PolyMC", repo: "polymc", color: "pink", icon: "used/pack-2/024-hearts.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 221 } },
  { params: { theme: "postbox", title: "Postbox", repo: "postbox", color: "yellow", icon: "used/pack-4/038-hermes-2.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 543 } },
  { params: { theme: "powerlevel10k", title: "Powerlevel10k", repo: "powerlevel10k", color: "cyan", icon: "used/pack-9/016-hook.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4912 } },
  { params: { theme: "powershell-ise", title: "PowerShell ISE", repo: "powershell-ise", color: "yellow", icon: "used/pack-3/040-sandglass.svg", platform: ["windows"], categories: ["all", "terminals"], legacyViews: 0 } },
  { params: { theme: "powershell", title: "PowerShell", repo: "powershell", color: "purple", icon: "used/pack-5/046-magic trick.svg", platform: ["all"], synonyms: ["cmd.exe"], categories: ["all", "terminals"], legacyViews: 66911 } },
  { params: { theme: "prism", title: "Prism", repo: "prism", color: "orange", icon: "used/pack-3/034-pot.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3893 } },
  { params: { theme: "prompt", title: "Prompt", repo: "prompt", color: "purple", icon: "used/pack-13/046-night.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 0 } },
  { params: { theme: "protonmail", title: "Protonmail", color: "cyan", repo: "protonmail", icon: "used/pack-2/028-glove.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "psychopy", title: "PsychoPy", repo: "psychopy", color: "orange", icon: "used/pack-10/049-serial-killer.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 329 } },
  { params: { theme: "pygments", title: "Pygments", repo: "pygments", color: "cyan", icon: "used/pack-1/039-ghost.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 7032 } },
  { params: { theme: "pythonista", title: "Pythonista", repo: "pythonista", color: "purple", icon: "used/pack-6/048-grave.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 11018 } },
  { params: { theme: "pywal", title: "Pywal", repo: "pywal", color: "orange", icon: "used/pack-5/005-magic-broom.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1347 } },
  { params: { theme: "qbittorrent", title: "QBittorrent", repo: "qbittorrent", color: "orange", icon: "used/pack-10/010-candle.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 79666 } },
  { params: { theme: "qt5", title: "qt5", repo: "qt5", color: "orange", icon: "used/pack-7/043-candles.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 5029 } },
  { params: { theme: "qtcreator", title: "Qt Creator", repo: "qtcreator", color: "cyan", icon: "used/pack-5/024-cauldron.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 51366 } },
  { params: { theme: "qterminal", title: "Qterminal", repo: "qterminal", color: "yellow", icon: "used/pack-9/046-muffin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "quassel", title: "Quassel", repo: "quassel", color: "cyan", icon: "used/pack-4/046-evil.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3861 } },
  { params: { theme: "quiver", title: "Quiver", repo: "quiver", color: "orange", icon: "used/pack-5/041-guillotine.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 4489 } },
  { params: { theme: "qutebrowser", title: "Qutebrowser", repo: "qutebrowser", color: "purple", icon: "used/pack-5/015-box.svg", platform: ["all"], categories: ["all", "browsers"], legacyViews: 7550 } },
  { params: { theme: "R", title: "R", repo: "dRacula", color: "cyan", icon: "used/pack-13/002-dracula-hex.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 572 } },
  { params: { theme: "ranger", title: "ranger", repo: "ranger", color: "pink", icon: "used/pack-9/019-brain.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2664 } },
  { params: { theme: "renoise", title: "ReNoise", repo: "renoise", color: "cyan", icon: "used/pack-8/047-computer.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1683 } },
  { params: { theme: "replugged", title: "Replugged", repo: "replugged", color: "purple", icon: "used/pack-2/025-tetris.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "revolt", title: "Revolt", repo: "revolt", color: "cyan", icon: "used/pack-9/030-coffin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 454 } },
  { params: { theme: "revolution-irc", title: "Revolution IRC", repo: "revolution-irc", color: "yellow", icon: "used/pack-9/008-trident.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 319 } },
  { params: { theme: "rime", title: "Rime", color: "pink", repo: "rime", icon: "used/pack-2/037-gaming.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "rio-terminal", title: "Rio Terminal", color: "cyan", repo: "rio-terminal", icon: "used/pack-12/028-kraken.svg", platform: ["all"], categories: ["all", "terminal"], legacyViews: 0 } },
  { params: { theme: "ripcord", title: "Ripcord", repo: "ripcord", color: "cyan", icon: "used/pack-10/042-knife.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 969 } },
  { params: { theme: "roam-research", title: "Roam Research", repo: "roam-research", color: "purple", icon: "used/pack-5/050-circle.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4366 } },
  { params: { theme: "rofi", title: "rofi", repo: "rofi", color: "purple", icon: "used/pack-7/028-lollipop.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 13546 } },
  { params: { theme: "rstudio", title: "RStudio", repo: "rstudio", color: "purple", icon: "used/pack-9/014-living-dead.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3300 } },
  { params: { theme: "runjs", title: "RunJs", repo: "runjs", color: "orange", icon: "used/pack-4/030-chariot.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 89 } },
  { params: { theme: "sandpack", title: "Sandpack", repo: "sandpack", color: "yellow", icon: "used/pack-3/007-castle.svg", platform: ["all"], categories: ["all", "others", "editors"], legacyViews: 193 } },
  { params: { theme: "scrivener", title: "Scrivener", repo: "scrivener", color: "cyan", icon: "used/pack-3/015-feather.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 328 } },
  { params: { theme: "sequel-ace", title: "Sequel Ace", repo: "sequel-ace", color: "orange", icon: "used/pack-9/001-moon.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 538 } },
  { params: { theme: "sequel-pro", title: "Sequel Pro", repo: "sequel-pro", color: "orange", icon: "used/pack-5/012-spell book.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 15860 } },
  { params: { theme: "serenityos", title: "SerenityOS", repo: "serenityos", color: "purple", icon: "used/pack-8/014-galaxy.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 532 } },
  { params: { theme: "sidenotes", title: "SideNotes", repo: "sidenotes", color: "yellow", icon: "used/pack-9/050-knife.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 1151 } },
  { params: { theme: "sioyek", title: "Sioyek", repo: "sioyek", color: "cyan", icon: "used/pack-5/023-mask.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 152 } },
  { params: { theme: "sketch", title: "Sketch", repo: "sketch", color: "cyan", icon: "used/pack-3/025-magic-wand-1.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 2350 } },
  { params: { theme: "slack", title: "Slack", repo: "slack", color: "cyan", icon: "used/pack-1/047-cleaver.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 114299 } },
  { params: { theme: "smartgit", title: "SmartGit", color: "green", repo: "smartgit", icon: "used/pack-8/026-alien.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 0 } },
  { params: { theme: "sniffnet", title: "Sniffnet", color: "purple", repo: "sniffnet", icon: "used/pack-3/029-enchanted-mirror.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "snippetslab", title: "SnippetsLab", repo: "snippetslab", color: "purple", icon: "used/pack-5/037-powder.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 328 } },
  { params: { theme: "solidworks", title: "SolidWorks", repo: "solidworks", color: "cyan", icon: "used/pack-10/044-monster-1.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 980 } },
  { params: { theme: "spacemacs", title: "Spacemacs", repo: "spacemacs", color: "orange", icon: "used/pack-8/018-planet.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3094 } },
  { params: { theme: "speedcrunch", title: "SpeedCrunch", repo: "speedcrunch", color: "pink", icon: "used/pack-2/005-slot machine.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "spicetify", title: "Spicetify", repo: "spicetify", color: "cyan", icon: "used/pack-4/020-mandolin.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 478 } },
  { params: { theme: "spotify-tui", title: "Spotify TUI", repo: "spotify-tui", color: "orange", icon: "used/pack-7/031-sweets.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 9993 } },
  { params: { theme: "spyder-ide", title: "Spyder IDE", repo: "spyder-ide", color: "cyan", icon: "used/pack-10/002-spider.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1739 } },
  { params: { theme: "st", title: "st", repo: "st", color: "pink", icon: "used/pack-13/042-halloween.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "stackoverflow", title: "StackOverflow", repo: "stackoverflow", color: "orange", icon: "used/pack-5/026-candlestick.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 2151 } },
  { params: { theme: "standard-notes", title: "Standard Notes", repo: "standard-notes", color: "purple", icon: "used/pack-7/016-eyeball.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3419 } },
  { params: { theme: "starship", title: "Starship", repo: "starship", color: "green", icon: "used/pack-8/041-spaceship.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3169 } },
  { params: { theme: "steam", title: "Steam", repo: "steam", color: "purple", icon: "used/pack-5/049-target.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 27555 } },
  { params: { theme: "stirling-pdf", title: "Stirling PDF", repo: "stirling-pdf", color: "yellow", icon: "used/pack-3/028-mass.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "streamlit", title: "Streamlit", repo: "streamlit", color: "cyan", icon: "used/pack-10/025-monster.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1852 } },
  { params: { theme: "sublime", title: "Sublime", repo: "sublime", color: "cyan", icon: "used/pack-1/044-spider-web.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 158632 } },
  { params: { theme: "subsonic", title: "Subsonic", repo: "subsonic", color: "cyan", icon: "used/pack-3/033-plant.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "suckless-tabbed", title: "Suckless Tabbed", repo: "suckless-tabbed", color: "cyan", icon: "used/pack-9/007-zombie.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 82 } },
  { params: { theme: "sumatra-pdf", title: "Sumatra PDF", repo: "sumatra-pdf", color: "orange", icon: "used/pack-10/013-frankenstein.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 2814 } },
  { params: { theme: "swaylock", title: "Swaylock", repo: "swaylock", color: "purple", icon: "used/pack-2/027-shield.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "swiftui", title: "SwiftUI", repo: "swiftui", color: "cyan", icon: "used/pack-10/031-wizard-1.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 1370 } },
  { params: { theme: "tabletop-simulator", title: "Tabletop Simulator", repo: "tabletop-simulator", color: "pink", icon: "used/pack-2/048-cards.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3311 } },
  { params: { theme: "tailwind", title: "Tailwind", repo: "tailwind", color: "cyan", icon: "used/pack-10/034-moon.svg", platform: ["all"], categories: ["all", "others", "services"], legacyViews: 4335 } },
  { params: { theme: "telegram-android", title: "Telegram Android", repo: "telegram-android", color: "orange", icon: "used/pack-6/038-skull.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 13607 } },
  { params: { theme: "telegram-ios", title: "Telegram iOS", repo: "telegram-ios", color: "purple", icon: "used/pack-7/006-skeleton.svg", platform: ["osx"], categories: ["all", "social"], legacyViews: 6243 } },
  { params: { theme: "telegram", title: "Telegram", repo: "telegram", color: "orange", icon: "used/pack-4/036-hermes-1.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 111236 } },
  { params: { theme: "terminal", title: "Terminal.app", repo: "terminal-app", color: "purple", icon: "used/pack-1/035-cauldron.svg", platform: ["osx"], categories: ["all", "terminals"], legacyViews: 311241 } },
  { params: { theme: "terminator", title: "Terminator", repo: "terminator", color: "orange", icon: "used/pack-7/003-werewolf.svg", platform: ["linux", "osx"], categories: ["all", "terminals"], legacyViews: 9352 } },
  { params: { theme: "termite", title: "Termite", repo: "termite", color: "cyan", icon: "used/pack-3/037-voodoo-doll.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 3460 } },
  { params: { theme: "termux", title: "Termux", repo: "termux", color: "cyan", icon: "used/pack-7/022-mummy.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 12761 } },
  { params: { theme: "texshop", title: "TeXShop", repo: "texshop", color: "cyan", icon: "used/pack-9/022-ghost.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 638 } },
  { params: { theme: "texstudio", title: "TeXstudio", repo: "texstudio", color: "purple", icon: "used/pack-10/045-jack-o-lantern.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2357 } },
  { params: { theme: "textastic", title: "Textastic", repo: "textastic", color: "cyan", icon: "used/pack-9/006-frankenstein.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 427 } },
  { params: { theme: "textmate", title: "Textmate", repo: "textmate", color: "cyan", icon: "used/pack-1/038-tombstone.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 12643 } },
  { params: { theme: "textual", title: "Textual", repo: "textual", color: "cyan", icon: "used/pack-1/032-bat.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 4338 } },
  { params: { theme: "thelounge", title: "The Lounge", repo: "thelounge", color: "orange", icon: "used/pack-7/012-dead-tree.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1166 } },
  { params: { theme: "thonny", title: "Thonny", repo: "thonny", color: "orange", icon: "used/pack-4/042-hydra.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 7258 } },
  { params: { theme: "thumb-key", title: "ThumbKey", color: "purple", repo: "thumb-key", icon: "used/pack-10/022-wizard.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "thunderbird", title: "Thunderbird", repo: "thunderbird", color: "purple", icon: "used/pack-4/003-phoenix.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 4140 } },
  { params: { theme: "tiddlywiki", title: "TiddlyWiki", repo: "tiddlywiki", color: "purple", icon: "used/pack-5/035-tent.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2821 } },
  { params: { theme: "tig", title: "tig", repo: "tig", color: "green", icon: "used/pack-10/011-cauldron.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 0 } },
  { params: { theme: "tilix", title: "Tilix", repo: "tilix", color: "cyan", icon: "used/pack-2/046-ghost.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 7564 } },
  { params: { theme: "tint2", title: "tint2", repo: "tint2", color: "cyan", icon: "used/pack-5/009-potion.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 465 } },
  { params: { theme: "tmux", title: "tmux", repo: "tmux", color: "purple", icon: "used/pack-1/030-clown.svg", platform: ["linux", "osx"], categories: ["all", "others"], legacyViews: 38512 } },
  { params: { theme: "todoist", title: "Todoist", repo: "todoist", color: "yellow", icon: "used/pack-4/004-hephaestus.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "total-commander", title: "Total Commander", repo: "total-commander", color: "purple", icon: "used/pack-3/044-spell-1.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 4995 } },
  { params: { theme: "tower", title: "Tower", repo: "tower", color: "pink", icon: "used/pack-8/025-observatory.svg", platform: ["osx", "window"], categories: ["all", "others"], legacyViews: 1151 } },
  { params: { theme: "tridactyl", title: "Tridactyl", repo: "tridactyl", color: "purple", icon: "used/pack-1/021-candy-corn.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 132 } },
  { params: { theme: "tty", title: "TTY", repo: "tty", color: "cyan", icon: "used/pack-10/023-living-dead.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 2225 } },
  { params: { theme: "tumblr", title: "Tumblr", color: "purple", repo: "tumblr", icon: "used/pack-13/001-vampire.svg", platform: ["all"], categories: ["all", "social"], legacyViews: 0 } },
  { params: { theme: "tut", title: "tut", repo: "tut", color: "yellow", icon: "used/pack-3/036-rabbit.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "tym", title: "tym", repo: "tym", color: "purple", icon: "used/pack-9/002-crow.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 368 } },
  { params: { theme: "typora", title: "Typora", repo: "typora", color: "purple", icon: "used/pack-1/017-witch-1.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 6540 } },
  { params: { theme: "ueli", title: "Ueli", repo: "ueli", color: "cyan", icon: "used/pack-9/042-eye.svg", platform: ["osx", "windows"], categories: ["all", "others"], legacyViews: 460 } },
  { params: { theme: "ulauncher", title: "Ulauncher", repo: "ulauncher", color: "pink", icon: "used/pack-7/005-candies.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 5331 } },
  { params: { theme: "ulysses", title: "Ulysses", repo: "ulysses", color: "orange", icon: "used/pack-3/027-magician-hat-1.svg", platform: ["osx"], categories: ["all", "others"], legacyViews: 7012 } },
  { params: { theme: "unigram", title: "Unigram", repo: "unigram", color: "orange", icon: "used/pack-7/040-jack-o-lantern.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 677 } },
  { params: { theme: "unreal-engine", title: "Unreal Engine", repo: "unreal-engine", color: "orange", icon: "used/pack-9/017-fangs.svg", platform: ["all"], categories: ["all", "ides", "services"], legacyViews: 1397 } },
  { params: { theme: "uptime-kuma", title: "Uptime Kuma", repo: "uptime-kuma", color: "cyan", icon: "used/pack-10/036-werewolf.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "vim", title: "Vim", repo: "vim", color: "purple", icon: "used/pack-1/040-zombie-1.svg", platform: ["all"], synonyms: ["neovim", "gvim"], categories: ["all", "editors", "ides"], legacyViews: 312057 } },
  { params: { theme: "vimium", title: "Vimium", repo: "vimium", color: "purple", icon: "used/pack-3/013-chest-1.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 6256 } },
  { params: { theme: "vis", title: "vis", repo: "vis", color: "orange", icon: "used/pack-13/009-pumpkin.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "visual-basic", title: "Visual Basic 6", repo: "visual-basic-6", color: "yellow", icon: "used/pack-3/024-magic-wand.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 1336 } },
  { params: { theme: "visual-spigot", title: "Visual Spigot", repo: "visual-spigot", color: "purple", icon: "used/pack-10/018-owl.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 645 } },
  { params: { theme: "visual-studio-code", title: "Visual Studio Code", repo: "visual-studio-code", color: "orange", icon: "used/pack-1/048-frankenstein.svg", platform: ["all"], synonyms: ["vscode"], categories: ["all", "editors"], legacyViews: 314788 } },
  { params: { theme: "visual-studio", title: "Visual Studio", repo: "visual-studio", color: "purple", icon: "used/pack-1/041-skeleton.svg", platform: ["osx", "windows"], categories: ["all", "ides"], legacyViews: 192815 } },
  { params: { theme: "vital", title: "Vital", repo: "vital", color: "purple", icon: "used/pack-4/049-lyre.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 170 } },
  { params: { theme: "vivado", title: "Vivado", repo: "vivado", color: "pink", icon: "used/pack-8/002-satellite.svg", platform: ["linux", "windows"], categories: ["all", "others"], legacyViews: 5392 } },
  { params: { theme: "vivaldi", title: "Vivaldi", repo: "vivaldi", color: "cyan", icon: "used/pack-1/003-broom.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 18989 } },
  { params: { theme: "vortex-mod-manager", title: "Vortex Mod Manager", repo: "vortex-mod-manager", color: "cyan", icon: "used/pack-2/011-game-controller.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 265 } },
  { params: { theme: "wallpaper", title: "Wallpaper", repo: "wallpaper", color: "cyan", icon: "used/pack-5/034-skull.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 102971 } },
  { params: { theme: "warp", title: "Warp", repo: "warp", color: "cyan", icon: "used/pack-10/003-haunted-house.svg", platform: ["osx"], categories: ["all", "terminals"], legacyViews: 1347 } },
  { params: { theme: "waybar", title: "Waybar", repo: "waybar", color: "purple", icon: "used/pack-5/031-magic cape.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "wezterm", title: "WezTerm", repo: "wezterm", color: "purple", icon: "used/pack-5/040-ticket.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 751 } },
  { params: { theme: "windows-terminal", title: "Windows Terminal", repo: "windows-terminal", color: "purple", icon: "used/pack-3/047-tube.svg", platform: ["windows"], categories: ["all", "terminals"], legacyViews: 125652 } },
  { params: { theme: "windterm", title: "WindTerm", repo: "windterm", color: "purple", icon: "used/pack-9/015-finger.svg", platform: ["all"], categories: ["all", "terminals"], legacyViews: 803 } },
  { params: { theme: "wing", title: "Wing", repo: "wing", color: "orange", icon: "used/pack-3/043-snake.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 1576 } },
  { params: { theme: "wob", title: "WOB", color: "pink", repo: "WOB", icon: "used/pack-1/020-halloween.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "wofi", title: "wofi", repo: "wofi", color: "pink", icon: "used/pack-7/050-poison.svg", platform: ["linux"], categories: ["all", "others"], legacyViews: 2729 } },
  { params: { theme: "wolfram-notebooks", title: "Wolfram Notebooks", repo: "wolfram-notebooks", color: "purple", icon: "used/pack-3/002-spellbook.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 2424 } },
  { params: { theme: "wordpress", title: "Wordpress", repo: "wordpress", color: "purple", icon: "used/pack-5/004-tarot.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 5030 } },
  { params: { theme: "wox", title: "Wox", repo: "wox", color: "cyan", icon: "used/pack-5/003-crystal ball.svg", platform: ["windows"], categories: ["all", "others"], legacyViews: 11790 } },
  { params: { theme: "wp", title: "WP", repo: "wp", color: "orange", icon: "used/pack-4/028-column.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 87 } },
  { params: { theme: "xchat", title: "XChat", repo: "xchat", color: "orange", icon: "used/pack-6/001-coffin.svg", platform: ["linux", "windows"], categories: ["all", "social"], legacyViews: 5723 } },
  { params: { theme: "xcode", title: "Xcode", repo: "xcode", color: "purple", icon: "used/pack-3/048-unicorn.svg", platform: ["osx"], categories: ["all", "ides", "editors"], legacyViews: 102804 } },
  { params: { theme: "xfce4-terminal", title: "Xfce4 Terminal", repo: "xfce4-terminal", color: "yellow", icon: "used/pack-7/029-clown.svg", platform: ["linux"], categories: ["all", "terminals"], legacyViews: 12022 } },
  { params: { theme: "xournalpp", title: "Xournal++", repo: "xournalpp", color: "pink", icon: "used/pack-7/013-witch.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3379 } },
  { params: { theme: "xresources", title: "Xresources", repo: "xresources", color: "purple", icon: "used/pack-5/047-mortar.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 24253 } },
  { params: { theme: "yakuake", title: "Yakuake", repo: "yakuake", color: "purple", icon: "used/pack-9/039-gift.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 0 } },
  { params: { theme: "youtube-music-desktop", title: "YouTube Music Desktop", repo: "youtube-music-desktop", color: "purple", icon: "used/pack-6/044-violin.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 496 } },
  { params: { theme: "youtube", title: "Youtube", repo: "youtube", color: "orange", icon: "used/pack-9/005-dracula.svg", platform: ["all"], categories: ["all", "services"], legacyViews: 3375 } },
  { params: { theme: "yunohost", title: "YunoHost", repo: "yunohost", color: "yellow", icon: "used/pack-5/014-scroll.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 183 } },
  { params: { theme: "zathura", title: "Zathura", repo: "zathura", color: "orange", icon: "used/pack-6/035-grave.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 3418 } },
  { params: { theme: "zed", title: "Zed", repo: "zed", color: "orange", icon: "used/pack-12/029-kappa.svg", platform: ["all"], categories: ["all", "editors"], legacyViews: 0 } },
  { params: { theme: "zellij", title: "Zellij", repo: "zellij", color: "cyan", icon: "used/pack-3/004-broom.svg", platform: ["linux", "osx"], categories: ["all", "ides"], legacyViews: 516 } },
  { params: { theme: "zsh-syntax-highlighting", title: "zsh-syntax-highlighting", repo: "zsh-syntax-highlighting", color: "yellow", icon: "used/pack-10/020-reaper.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 10231 } },
  { params: { theme: "zsh", title: "Zsh", repo: "zsh", color: "cyan", icon: "used/pack-1/034-eye.svg", platform: ["all"], categories: ["all", "others"], legacyViews: 276962 } }
];

export default paths;
