name: Dracula
description: 'A dark theme for Atom, Alfred, Brackets, Emacs, iTerm, Mintty, Notepad++, Slack, Sequel Pro, Sublime Text, Telegram, Textmate, Terminal.app, Ulysses, Vim, Visual Studio Code, WordPress, Wox, Xcode, and Zsh'
author: Zeno Rocha
url: https://draculatheme.com
