name: Dracula
description: 'A dark theme for Atom, Alfred, Brackets, Emacs, iTerm, Mintty, Slack, Sequel Pro, Sublime Text, Textmate, Terminal.app, Ulysses, Vim, Visual Studio Code, Xcode, and Zsh'
author: Zeno Rocha
url: https://draculatheme.com
