export const apps = [
  { value: "alacritty", label: "Alacritty" },
  { value: "emacs", label: "Emacs" },
  { value: "firefox", label: "Firefox" },
  { value: "gnome-terminal", label: "Gnome Terminal" },
  { value: "google-chrome", label: "Google Chrome" },
  { value: "hyper", label: "Hyper" },
  { value: "insomnia", label: "Insomnia" },
  { value: "iterm", label: "iTerm" },
  { value: "jetbrains", label: "JetBrains IDEs" },
  { value: "notepad-plus-plus", label: "Notepad++" },
  { value: "raycast", label: "Raycast" },
  { value: "slack", label: "Slack" },
  { value: "sublime", label: "Sublime Text" },
  { value: "terminal", label: "Terminal.app" },
  { value: "vim", label: "Vim" },
  { value: "vscode", label: "Visual Studio Code" },
  { value: "windows-terminal", label: "Windows Terminal" },
  { value: "xcode", label: "Xcode" },
  { value: "zed", label: "Zed" }
];
